const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const path = require('path');
const authRoutes = require('./routes/authRoutes');
const productRoutes = require('./routes/productRoutes');
const categoryRoutes = require('./routes/categoryRoutes');
const cartRoutes = require('./routes/cartRoutes');
const wishlistRoutes = require('./routes/wishlistRoutes');
const orderRoutes = require('./routes/orderRoutes');
const customerRoutes = require('./routes/customerRoutes');
const merchantRoutes = require('./routes/merchantRoutes');
const uploadRoutes = require('./routes/uploadRoutes');
const configRoutes = require('./routes/configRoutes');
const accountRoutes = require('./routes/accountRoutes');
const bannerRoutes = require('./routes/bannerRoutes');
const campaignRoutes = require('./routes/campaignRoutes');
const homepageRoutes = require('./routes/homepageRoutes');
const notificationRoutes = require('./routes/notificationRoutes');
const couponRoutes = require('./routes/couponRoutes');
const offerRoutes = require('./routes/offerRoutes');
const giftCardRoutes = require('./routes/giftCardRoutes');
const supportRoutes = require('./routes/supportRoutes');
const aiRoutes = require('./routes/aiRoutes');
const customerChatRoutes = require('./routes/customerChatRoutes');
const modelsRoutes = require('./routes/models');
const liveRoutes = require('./routes/liveRoutes');
const liveObsRoutes = require('./routes/liveObsRoutes');
const liveProductRoutes = require('./routes/liveProductRoutes');
const trendRoutes = require('./routes/trendRoutes');
const trendEventRoutes = require('./routes/trendEventRoutes');
const merchantTrendRoutes = require('./routes/merchantTrendRoutes');
const trendVideoRoutes = require('./routes/trendVideoRoutes');
const storyRoutes = require('./routes/storyRoutes');
const paymentMethodRoutes = require('./routes/paymentMethodRoutes');
const paymentMethodsPublicRoutes = require('./routes/paymentMethodsPublicRoutes');
const returnRoutes = require('./routes/returnRoutes');
const loyaltyRoutes = require('./routes/loyaltyRoutes');
const settingsRoutes = require('./routes/settingsRoutes');
const staffRoutes = require('./routes/staffRoutes');
const errorHandler = require('./middleware/errorHandler');
const sanitizeInput = require('./middleware/sanitizeInput');
const { apiLimiter, liveLimiter } = require('./middleware/rateLimiters');
const app = express();

app.set('trust proxy', 1);
app.use(helmet({ contentSecurityPolicy: { directives: { 'img-src': ["'self'", 'data:', 'blob:', 'https://images.unsplash.com', 'https://res.cloudinary.com'], 'media-src': ["'self'", 'blob:', 'https:', 'https://res.cloudinary.com'] } } }));
app.use(express.json({ limit: '32mb' }));
app.use(sanitizeInput);
const allowedOrigins = (process.env.ALLOWED_ORIGINS || '').split(',').map((origin) => origin.trim().replace(/\/$/, '')).filter(Boolean);
const railwayFrontendOrigins = ['https://enchanting-miracle-production-a5d2.up.railway.app','https://lovely-serenity-production.up.railway.app','https://independent-flow-production.up.railway.app'];
const productionOrigins = [...new Set([...allowedOrigins, ...railwayFrontendOrigins])];
const isAllowedOrigin = (origin) => { if (!origin) return true; const normalizedOrigin = origin.replace(/\/$/, ''); if (productionOrigins.includes(normalizedOrigin)) return true; return process.env.NODE_ENV !== 'production' && allowedOrigins.length === 0; };
app.use(cors({ origin(origin, callback) { return isAllowedOrigin(origin) ? callback(null, true) : callback(null, false); }, credentials: true, optionsSuccessStatus: 204 }));
if (process.env.NODE_ENV !== 'production') app.use(morgan('dev'));
app.get('/api/health', (req, res) => res.json({ status: 'ok' }));
app.use('/api/live', liveLimiter);
app.use('/api', apiLimiter);
const uploadsDirectory = path.join(__dirname, 'uploads');
app.use('/uploads', (req, res, next) => { res.setHeader('Cross-Origin-Resource-Policy', 'cross-origin'); next(); }, express.static(uploadsDirectory, { fallthrough: true, maxAge: '1d' }));
app.use('/api/live', (req, res, next) => { res.set('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0'); res.set('Pragma', 'no-cache'); res.set('Expires', '0'); res.set('Surrogate-Control', 'no-store'); res.removeHeader('ETag'); next(); });
app.use('/api/auth', authRoutes); app.use('/api/account', accountRoutes); app.use('/api/products', productRoutes); app.use('/api/categories', categoryRoutes); app.use('/api/cart', cartRoutes); app.use('/api/wishlist', wishlistRoutes); app.use('/api/orders', orderRoutes); app.use('/api/customers', customerRoutes); app.use('/api/merchants', merchantRoutes); app.use('/api/upload', uploadRoutes); app.use('/api/config', configRoutes); app.use('/api/settings', settingsRoutes); app.use('/api/banners', bannerRoutes); app.use('/api/campaigns', campaignRoutes); app.use('/api/homepage', homepageRoutes); app.use('/api/notifications', notificationRoutes); app.use('/api/coupons', couponRoutes); app.use('/api/offers', offerRoutes); app.use('/api/gift-cards', giftCardRoutes); app.use('/api/support', supportRoutes); app.use('/api/ai', aiRoutes); app.use('/api/chat', customerChatRoutes); app.use('/api/models', modelsRoutes); app.use('/api/live', liveRoutes); app.use('/api/live-obs', liveObsRoutes); app.use('/api/live', liveProductRoutes); app.use('/api/trend', trendRoutes); app.use('/api/trend/events', trendEventRoutes); app.use('/api/trend/merchant', merchantTrendRoutes); app.use('/api/trend/video-upload', trendVideoRoutes); app.use('/api/stories', storyRoutes); app.use('/api/payment-methods', paymentMethodsPublicRoutes); app.use('/api/payment-methods', paymentMethodRoutes); app.use('/api/payment-methods/admin', paymentMethodRoutes); app.use('/api/returns', returnRoutes); app.use('/api/loyalty', loyaltyRoutes); app.use('/api/staff', staffRoutes);
app.use((req, res) => res.status(404).json({ message: 'المسار غير موجود' }));
app.use(errorHandler);
module.exports = app;
