import React,{useEffect,useMemo,useState}from'react';import{NavLink,Outlet,useLocation,useNavigate}from'react-router-dom';import{useAdminAuth}from'../context/AdminAuthContext';import{canAccess}from'../utils/permissions';import api from'../api/client';import CommandCenter from'./CommandCenter';import LiveEngagementPanel from'./LiveEngagementPanel';import'./AdminShell.css';
const groups=[
 {title:'الرئيسية',links:[['/','لوحة التحكم','⌂',true,'dashboard'],['orders','الطلبات','🛍️',false,'orders'],['customers','العملاء','👤',false,'customers']]},
 {title:'المتجر',links:[['products','المنتجات','📦',false,'products'],['products/add','إضافة منتج','＋',false,'products','create'],['categories','الأقسام','▦',false,'products'],['store-customizer','تخصيص المتجر','✦',false,'settings'],['payment-methods','طرق الدفع','▣',false,'payments']]},
 {title:'التسويق والنمو',links:[['banners','البنرات','🖼️',false,'marketing'],['campaigns','الحملات','📣',false,'marketing'],['offers','العروض والخصومات','％',false,'marketing'],['coupons','الكوبونات','★',false,'marketing'],['gift-cards','بطاقات الهدايا','🎁',false,'marketing'],['loyalty','النقاط والولاء','◆',false,'marketing']]},
 {title:'التجار والشركاء',links:[['merchants','التجار','🏪',false,'merchants'],['models','المودلز','◎',false,'merchants']]},
 {title:'خدمة العملاء',links:[['customer-service','مركز خدمة العملاء','🎧',false,'support'],['support-tickets','تذاكر الدعم','▣',false,'support']]},
 {title:'المحتوى والبث',links:[['studio','استديو MYBRAND','✦',false,'marketing'],['trend','Trend Hub','↗',false,'marketing'],['live','البث المباشر','●',false,'marketing']]},
 {title:'الإدارة والنظام',links:[['staff','الفريق والصلاحيات','✓',false,'staff'],['reports','التقارير','▥',false,'reports'],['settings','الإعدادات','⚙',false,'settings']]}];
const pageLabels=Object.fromEntries(groups.flatMap(g=>g.links.map(([path,label])=>[path,label])));function Icon({name}){return <span aria-hidden="true" style={{width:20,display:'inline-flex',justifyContent:'center',fontSize:15}}>{name}</span>}function target(path){return path==='/'?'/':`/${path}`}
const attentionCount=orders=>orders.filter(o=>o?.status==='pending'||o?.status==='processing'||o?.status==='shipped'||(o?.paymentMethod==='vodafone_cash'&&o?.paymentStatus!=='paid')).length;
export default function Layout(){const{user,logout}=useAdminAuth();const location=useLocation();const navigate=useNavigate();const[badges,setBadges]=useState({orders:0});const canViewOrders=canAccess(user,'orders','view');const visibleGroups=useMemo(()=>groups.map(g=>({...g,links:g.links.filter(([path,, , , moduleName,action])=>canAccess(user,path,action||'view'))})).filter(g=>g.links.length),[user]);useEffect(()=>{let active=true;const load=async()=>{if(!canViewOrders)return;try{const r=await api.get('/orders');if(!active)return;setBadges({orders:attentionCount(r.data?.orders||[])})}catch{}};load();const id=setInterval(load,30000);return()=>{active=false;clearInterval(id)}},[canViewOrders]);const cleanPath=location.pathname.replace(/^\//,'');const label=cleanPath.startsWith('merchants/')?'تفاصيل التاجر':pageLabels[cleanPath]||'لوحة التحكم';const section=groups.find(g=>g.links.some(([path])=>path===cleanPath||cleanPath.startsWith(`${path}/`)))?.title||'لوحة التحكم';const showLiveEngagement=cleanPath==='live';return <div className="admin-shell" dir="rtl"><aside className="admin-sidebar"><div className="side-logo"><div className="side-mark">M</div><div><b>MYBRAND</b><span>مركز الإدارة</span></div></div><nav className="side-nav">{visibleGroups.map(group=><div className="nav-group" key={group.title}><div className="nav-group-label">{group.title}</div>{group.links.map(([path,text,icon,end])=><NavLink key={path} to={target(path)} end={!!end} className={({isActive})=>`side-link ${isActive?'active':''}`}><Icon name={icon}/><span>{text}</span>{path==='orders'&&badges.orders>0&&<em>{badges.orders}</em>}</NavLink>)}</div>)}</nav><div className="side-bottom"><div className="admin-mini"><div className="admin-avatar">{(user?.name||'A').slice(0,1).toUpperCase()}</div><div><b>{user?.name||'أدمن المتجر'}</b><span>{user?.email||'admin@mybrand.com'}</span></div></div></div></aside><div className="admin-main-wrap"><header className="admin-topbar"><div className="breadcrumb"><span>{section}</span><b>{label}</b></div><div className="top-actions"><button className="top-icon" title="بحث" onClick={()=>window.dispatchEvent(new Event('open-admin-command-center'))}>⌕</button>{canViewOrders&&<button className="top-icon admin-orders-shortcut" title={badges.orders>0?`طلبات تحتاج إجراء: ${badges.orders}`:'الطلبات'} onClick={()=>navigate('/orders')}>🛍️{badges.orders>0&&<em>{badges.orders}</em>}</button>}<button className="logout" onClick={logout}>خروج</button></div></header><main className="admin-main"><Outlet/>{showLiveEngagement&&<LiveEngagementPanel/>}</main></div><CommandCenter/></div>}
