import React,{useEffect,useState}from'react';import{NavLink,Outlet,useLocation}from'react-router-dom';import{useAdminAuth}from'../context/AdminAuthContext';import api from'../api/client';import CommandCenter from'./CommandCenter';import LiveEngagementPanel from'./LiveEngagementPanel';import'./AdminShell.css';
const groups=[
 {title:'الرئيسية',links:[['/','لوحة التحكم','⌂',true],['orders','الطلبات','🛍️'],['customers','العملاء','👤']]},
 {title:'المتجر',links:[['products','المنتجات','📦'],['categories','الأقسام','▦'],['store-customizer','تخصيص المتجر','✦'],['payment-methods','طرق الدفع','▣']]},
 {title:'التسويق',links:[['banners','البنرات','🖼️'],['campaigns','الحملات','📣'],['offers','العروض والخصومات','％'],['coupons','الكوبونات','★'],['gift-cards','بطاقات الهدايا','🎁'],['loyalty','النقاط والولاء','◆']]},
 {title:'التجار والشركاء',links:[['merchants','التجار','🏪'],['models','المودلز','◎']]},
 {title:'خدمة العملاء',links:[['customer-service','خدمة العملاء','🎧']]},
 {title:'المحتوى والبث',links:[['studio','استديو MYBRAND','✦'],['trend','Trend Hub','↗'],['live','البث المباشر','●']]},
 {title:'الإدارة والنظام',links:[['staff','الفريق والصلاحيات','✓'],['reports','التقارير','▥'],['settings','الإعدادات','⚙']]}
];
const pageLabels=Object.fromEntries(groups.flatMap(g=>g.links.map(([path,label])=>[path,label])));function Icon({name}){return <span aria-hidden="true" style={{width:20,display:'inline-flex',justifyContent:'center',fontSize:15}}>{name}</span>}function target(path){return path==='/'?'/':`/${path}`}
export default function Layout(){const{user,logout}=useAdminAuth();const location=useLocation();const[badges,setBadges]=useState({orders:0});useEffect(()=>{api.get('/orders').then(r=>setBadges({orders:r.data?.total||r.data?.orders?.length||0})).catch(()=>{})},[]);const cleanPath=location.pathname.replace(/^\//,'');const label=cleanPath.startsWith('merchants/')?'تفاصيل التاجر':pageLabels[cleanPath]||'لوحة التحكم';const section=groups.find(g=>g.links.some(([path])=>path===cleanPath||cleanPath.startsWith(`${path}/`)))?.title||'لوحة التحكم';const showLiveEngagement=cleanPath==='live';return <div className="admin-shell" dir="rtl"><aside className="admin-sidebar"><div className="side-logo"><div className="side-mark">M</div><div><b>MYBRAND</b><span>مركز الإدارة</span></div></div><nav className="side-nav">{groups.map(group=><div className="nav-group" key={group.title}><div className="nav-group-label">{group.title}</div>{group.links.map(([path,text,icon,end])=><NavLink key={path} to={target(path)} end={!!end} className={({isActive})=>`side-link ${isActive?'active':''}`}><Icon name={icon}/><span>{text}</span>{path==='orders'&&badges.orders>0&&<em>{badges.orders}</em>}</NavLink>)}</div>)}</nav><div className="side-bottom"><div className="admin-mini"><div className="admin-avatar">{(user?.name||'A').slice(0,1).toUpperCase()}</div><div><b>{user?.name||'أدمن المتجر'}</b><span>{user?.email||'admin@mybrand.com'}</span></div></div></div></aside><div className="admin-main-wrap"><header className="admin-topbar"><div className="breadcrumb"><span>{section}</span><b>{label}</b></div><div className="top-actions"><button className="top-icon" title="بحث" onClick={()=>window.dispatchEvent(new Event('open-admin-command-center'))}>⌕</button><button className="top-icon" title="الإشعارات">♧</button><button className="logout" onClick={logout}>خروج</button></div></header><main className="admin-main"><Outlet/>{showLiveEngagement&&<LiveEngagementPanel/>}</main></div><CommandCenter/></div>}
