const crypto = require('crypto');
const Coupon = require('../models/Coupon');
const Product = require('../models/Product');
const Category = require('../models/Category');
const Banner = require('../models/Banner');
const Campaign = require('../models/Campaign');
const Offer = require('../models/Offer');
const Order = require('../models/Order');
const User = require('../models/User');

const allowedSections = ['/products','/orders','/customers','/merchants','/campaigns','/offers','/coupons','/customer-service','/categories','/banners'];
const orderStatuses = ['pending','confirmed','processing','shipped','delivered','cancelled'];
const safeText = (v,max=500) => String(v ?? '').trim().slice(0,max);
const safeCode = v => String(v||'').toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,24);
const cleanJson = t => { const m=String(t||'').match(/\{[\s\S]*\}/); if(!m)return null; try{return JSON.parse(m[0]);}catch{return null;} };
const slugify = v => safeText(v,120).toLowerCase().trim().replace(/[^a-z0-9\u0600-\u06ff]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80) || `item-${Date.now()}`;
const conversationStore = new Map();
const historyFor = req => { const key=String(req.headers.authorization||'').slice(-180)||req.ip||'anonymous'; const h=conversationStore.get(key)||[]; return {key,history:h}; };
const saveHistory = (key,history) => { conversationStore.set(key,history.slice(-16)); };
const safeMedia = (media=[]) => Array.isArray(media) ? media.slice(0,4).filter(m => m && typeof m.data === 'string' && m.data.startsWith('data:')).map(m => ({ data:m.data.slice(0,8_000_000), mimeType:safeText(m.mimeType||'',80), name:safeText(m.name||'media',120), type:m.type==='video'?'video':'image', uploadedUrl:safeText(m.uploadedUrl||'',1000) })) : [];
const dataUrlParts = data => { const m=String(data||'').match(/^data:([^;]+);base64,(.+)$/s); return m ? {mimeType:m[1],data:m[2]} : null; };

async function buildStoreInsights(){
  const [products,orders,customers]=await Promise.all([Product.find({}).select('nameAr nameEn price isActive isFeatured').lean(),Order.find({}).select('orderNumber user items total status createdAt').populate('user','name email').lean(),User.find({role:'customer'}).select('name email isActive createdAt').lean()]);
  const map=new Map(products.map(p=>[String(p._id),p])), stats=new Map(), customerSpend=new Map(); let revenue=0;
  for(const o of orders){if(o.status!=='cancelled')revenue+=Number(o.total)||0;if(o.user&&o.status!=='cancelled'){const id=String(o.user._id),s=customerSpend.get(id)||{name:o.user.name,email:o.user.email,orders:0,spend:0};s.orders++;s.spend+=Number(o.total)||0;customerSpend.set(id,s);}for(const i of o.items||[]){const id=String(i.product?._id||i.product||'');if(!id)continue;const s=stats.get(id)||{quantity:0,revenue:0};const q=Number(i.quantity)||0;s.quantity+=q;s.revenue+=q*(Number(i.price)||0);stats.set(id,s);}}
  return {summary:{products:products.length,activeProducts:products.filter(p=>p.isActive!==false).length,orders:orders.length,activeOrders:orders.filter(o=>!['delivered','cancelled'].includes(o.status)).length,customers:customers.length,revenue:Number(revenue.toFixed(2))},topProducts:[...stats.entries()].map(([id,s])=>({product:map.get(id)?.nameAr||map.get(id)?.nameEn||id,...s})).sort((a,b)=>b.revenue-a.revenue).slice(0,10),lowMovement:products.map(p=>({product:p.nameAr||p.nameEn||String(p._id),quantity:stats.get(String(p._id))?.quantity||0,revenue:stats.get(String(p._id))?.revenue||0})).sort((a,b)=>a.quantity-b.quantity).slice(0,10),activeOrders:orders.filter(o=>!['delivered','cancelled'].includes(o.status)).slice(0,15).map(o=>({orderNumber:o.orderNumber,status:o.status,total:o.total,customer:o.user?.name||o.user?.email||'—'})),topCustomers:[...customerSpend.values()].sort((a,b)=>b.spend-a.spend).slice(0,10)};
}

const callAI=async(input,system)=>{
  const geminiKey=String(process.env.GEMINI_API_KEY||'').trim(),media=safeMedia(input?.media);
  if(geminiKey){
    // Ignore stale Railway model values. The production target is Gemini 3.6 Flash.
    const model='gemini-3.6-flash';
    const userText=typeof input==='string'?input:JSON.stringify({...input,media:media.map(m=>({name:m.name,type:m.type,mimeType:m.mimeType,uploadedUrl:m.uploadedUrl||undefined,attached:true,data:undefined}))}),parts=[{text:userText}];
    for(const item of media){const parsed=dataUrlParts(item.data);if(parsed)parts.push({inlineData:{mimeType:parsed.mimeType,data:parsed.data}});}
    const body={systemInstruction:{parts:[{text:system}]},contents:[{role:'user',parts}],generationConfig:{temperature:0.25,maxOutputTokens:4096}};
    const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(geminiKey)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
    const d=await r.json();
    if(!r.ok)throw Object.assign(new Error(d?.error?.message||`Gemini request failed (${r.status})`),{code:'AI_REQUEST_FAILED',status:r.status,provider:'gemini'});
    const text=(d?.candidates||[]).flatMap(c=>c?.content?.parts||[]).map(p=>p?.text||'').join('').trim();
    if(!text)throw Object.assign(new Error('Gemini returned an empty response'),{code:'AI_EMPTY_RESPONSE',provider:'gemini'});
    return text;
  }
  if(!process.env.OPENAI_API_KEY)throw Object.assign(new Error('No AI provider is configured'),{code:'AI_NOT_CONFIGURED'});const model=process.env.OPENAI_ADMIN_MODEL||'gpt-5.6-luna',userContent=[{type:'input_text',text:typeof input==='string'?input:JSON.stringify({...input,media:media.map(m=>({name:m.name,type:m.type,mimeType:m.mimeType,uploadedUrl:m.uploadedUrl||undefined,attached:true,data:undefined}))})}];for(const item of media){if(item.type==='image')userContent.push({type:'input_image',image_url:item.data});else userContent.push({type:'input_text',text:`تم إرفاق فيديو باسم ${item.name} (${item.mimeType}).`});}const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model,input:[{role:'system',content:[{type:'input_text',text:system}]},{role:'user',content:userContent}]})});const d=await r.json();if(!r.ok)throw Object.assign(new Error(d?.error?.message||'OpenAI request failed'),{code:'AI_REQUEST_FAILED',status:r.status,provider:'openai'});return d.output_text||'';
};

exports.adminInsights=async(req,res)=>{try{const insights=await buildStoreInsights();let recommendation='',mode='data';try{recommendation=await callAI(insights,'أنت محلل أعمال لمتجر MYBRAND. حلل البيانات المرفقة فقط، لا تخترع أرقامًا، وأعط 3 توصيات عملية قصيرة بالعربية.');mode=process.env.GEMINI_API_KEY?'gemini':'openai';}catch(e){if(e.code!=='AI_NOT_CONFIGURED')console.error('AI insights:',e.message);else mode='data';}return res.json({insights,recommendation,mode,aiAvailable:Boolean(process.env.GEMINI_API_KEY||process.env.OPENAI_API_KEY)});}catch(e){console.error(e);return res.status(500).json({message:'تعذر تحليل بيانات المتجر.'});}};
exports.adminChat=async(req,res)=>{const message=safeText(req.body?.message,2000),context=req.body?.context||{},media=safeMedia(req.body?.media);if(!message&&!media.length)return res.status(400).json({message:'اكتب طلبك أو أرفق صورة/فيديو أولًا'});const {key,history}=historyFor(req),nextHistory=[...history,{role:'user',text:message||'حلل المرفقات المضافة'}];try{const insights=await buildStoreInsights(),reply=await callAI({message,context,history:nextHistory.slice(-12),storeInsights:insights,media},'أنت MYBRAND AI داخل لوحة تحكم متجر. افهم السؤال من سياقه ولا تعتمد على كلمات مفتاحية. استخدم بيانات المتجر المرفقة عند الحاجة. إذا أرفق المدير صورة أو فيديو فحللهما عندما يكون ذلك مفيدًا، واستخرج منهما بيانات المنتج أو التصميم أو العرض. لا تدّعي تنفيذ أي تغيير؛ التنفيذ يتم عبر أدوات منفصلة. إذا كان الطلب ينقصه شيء مهم اسأل سؤالًا توضيحيًا. أجب بالعربية الطبيعية، ولا تكرر رسالة ترحيب أو نصًا ثابتًا.');saveHistory(key,[...nextHistory,{role:'assistant',text:reply}]);return res.json({reply:reply||'لم أجد إجابة كافية، وضّح طلبك أكثر.',mode:process.env.GEMINI_API_KEY?'gemini':'openai',mediaCount:media.length});}catch(e){if(e.code==='AI_NOT_CONFIGURED')return res.status(503).json({message:'الذكاء الاصطناعي غير مفعّل على الخادم. أضف GEMINI_API_KEY في Railway ثم أعد النشر.'});console.error('AI chat:',e.message);return res.status(502).json({message:`تعذر الاتصال بالذكاء الاصطناعي الآن: ${e.message}`});}};
exports.prepareAdminAction=async(req,res)=>{const message=safeText(req.body?.message,2000),context=req.body?.context||{},media=safeMedia(req.body?.media);if(!message&&!media.length)return res.status(400).json({message:'اكتب ما تريد تنفيذه أو أرفق الوسائط أولًا'});try{const system=`أنت مخطط إجراءات آمن داخل MYBRAND. أعد JSON فقط دون Markdown. الأنواع المسموحة: create_product, create_category, create_coupon, create_banner, create_campaign, create_offer, update_product, update_banner, update_order_status, open_section. كل تغيير بيانات requiresConfirmation=true. لا تغيّر مخزون المنتج أو التاجر أو القسم. لا تغيّر صورة البانر مباشرة إلا عند الإنشاء إذا كان هناك uploadedUrl مرفق. حالات الطلب: ${orderStatuses.join(',')}. الأقسام: ${allowedSections.join(',')}. إذا كانت هناك صورة أو فيديو مرفق، حللهما. استخدم uploadedUrl للصور المرفوعة داخل params.images أو params.image عندما يكون متاحًا. إذا كان هناك فيديو مرفوع كرابط استخدمه في params.videoUrl. إذا كان الطلب لا يطلب تغييرًا فعليًا أعد {"action":null,"reply":"..."}. لإنشاء المنتج: الاسم العربي والإنجليزي والslug والقسم والسعر مطلوبة. لإنشاء القسم: nameAr,nameEn,slug مطلوبة. لإنشاء البانر: titleAr وimage مطلوبة. لإنشاء العرض: nameAr,discountType,discountValue,scope,startDate,endDate مطلوبة، وإذا كان النطاق product/category/merchant يجب تحديد الهدف. اجعل params دقيقة وقابلة للتنفيذ.`;const raw=await callAI({message,context,media},system),parsed=cleanJson(raw),action=parsed?.action;if(!action)return res.json({action:null,reply:parsed?.reply||'هذا الطلب لا يحتاج إجراءً إداريًا.',mode:process.env.GEMINI_API_KEY?'gemini':'openai'});action.params=action.params||{};action.requiresConfirmation=action.type!=='open_section';if(action.type==='open_section'&&!allowedSections.includes(action.params.path))return res.json({action:null,reply:'القسم المطلوب غير متاح.',mode:process.env.GEMINI_API_KEY?'gemini':'openai'});if(action.type==='update_order_status'&&!orderStatuses.includes(action.params.status))return res.json({action:null,reply:'حالة الطلب غير صالحة.',mode:process.env.GEMINI_API_KEY?'gemini':'openai'});return res.json({action,mode:process.env.GEMINI_API_KEY?'gemini':'openai'});}catch(e){return res.status(e.code==='AI_NOT_CONFIGURED'?503:502).json({message:e.code==='AI_NOT_CONFIGURED'?'الذكاء الاصطناعي غير مفعّل على الخادم. أضف GEMINI_API_KEY في Railway ثم أعد النشر.':`تعذر تجهيز الإجراء بالذكاء الاصطناعي الآن: ${e.message}`});}};

exports.executeAdminAction=async(req,res)=>{const a=req.body?.action;if(!a?.type)return res.status(400).json({message:'الإجراء غير صالح'});const p=a.params||{};
 if(a.type!=='open_section' && (a.requiresConfirmation !== true || a.confirmed !== true)) return res.status(400).json({message:'يجب تأكيد الإجراء من المدير قبل تنفيذ أي تغيير.'});
 if(a.type==='open_section'){if(!allowedSections.includes(p.path))return res.status(400).json({message:'القسم غير مسموح'});return res.json({ok:true,type:a.type,path:p.path,message:'تم تجهيز الانتقال للقسم.'});}
 if(a.type==='create_category'){const nameAr=safeText(p.nameAr,120),nameEn=safeText(p.nameEn||p.nameAr,120),slug=slugify(p.slug||nameEn);if(!nameAr)return res.status(400).json({message:'اسم القسم بالعربي مطلوب.'});try{const c=await Category.create({nameAr,nameEn,slug,image:safeText(p.image,1000),isActive:true});return res.json({ok:true,type:a.type,category:{id:c._id,nameAr:c.nameAr},message:`تم إنشاء القسم «${c.nameAr}» بنجاح.`});}catch(e){if(e?.code===11000)return res.status(409).json({message:'Slug القسم مستخدم بالفعل.'});throw e;}}
 if(a.type==='create_product'){const nameAr=safeText(p.nameAr,180),nameEn=safeText(p.nameEn||p.nameAr,180),price=Number(p.price),categoryInput=safeText(p.category,180);if(!nameAr||!Number.isFinite(price)||price<0||!categoryInput)return res.status(400).json({message:'لإنشاء المنتج أحتاج الاسم العربي والسعر والقسم.'});const category=await Category.findById(categoryInput).catch(()=>null)||await Category.findOne({$or:[{nameAr:categoryInput},{nameEn:categoryInput},{slug:slugify(categoryInput)}]});if(!category)return res.status(404).json({message:'لم أجد القسم المطلوب للمنتج.'});try{const product=await Product.create({nameAr,nameEn,slug:slugify(p.slug||nameEn),category:category._id,price,compareAtPrice:p.compareAtPrice==null?null:Number(p.compareAtPrice),descriptionAr:safeText(p.descriptionAr,1000),images:Array.isArray(p.images)?p.images.filter(Boolean).slice(0,8):[],videoUrl:safeText(p.videoUrl,1000),videoPoster:safeText(p.videoPoster,1000),stock:Math.max(0,Number(p.stock)||0),tags:Array.isArray(p.tags)?p.tags.map(x=>safeText(x,40)).filter(Boolean).slice(0,20):[],isActive:p.isActive!==false,isFeatured:Boolean(p.isFeatured),status:'approved'});return res.json({ok:true,type:a.type,product:{id:product._id,nameAr:product.nameAr},message:`تم إنشاء المنتج «${product.nameAr}» بنجاح.`});}catch(e){if(e?.code===11000)return res.status(409).json({message:'Slug المنتج مستخدم بالفعل.'});throw e;}}
 if(a.type==='create_banner'){const titleAr=safeText(p.titleAr,180),image=safeText(p.image,1000);if(!titleAr||!image)return res.status(400).json({message:'عنوان البانر والصورة مطلوبان.'});const b=await Banner.create({titleAr,subtitleAr:safeText(p.subtitleAr,300),image,buttonTextAr:safeText(p.buttonTextAr,100),buttonLink:safeText(p.buttonLink,500),sortOrder:Number(p.sortOrder)||0,isActive:p.isActive!==false});return res.json({ok:true,type:a.type,banner:{id:b._id,titleAr:b.titleAr},message:'تم إنشاء البانر بنجاح.'});}
 if(a.type==='create_offer'){const type=p.discountType==='fixed'?'fixed':'percentage',value=Number(p.discountValue),scope=['product','category','merchant','store'].includes(p.scope)?p.scope:'store',start=new Date(p.startDate),end=new Date(p.endDate);if(!safeText(p.nameAr,160)||!Number.isFinite(value)||value<=0||!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<start)return res.status(400).json({message:'بيانات العرض غير مكتملة أو التواريخ غير صالحة.'});const targetProduct=scope==='product'?p.targetProduct||null:null,targetCategory=scope==='category'?p.targetCategory||null:null,targetMerchant=scope==='merchant'?p.targetMerchant||null:null;if((scope==='product'&&!targetProduct)||(scope==='category'&&!targetCategory)||(scope==='merchant'&&!targetMerchant))return res.status(400).json({message:'يجب تحديد العنصر المستهدف لهذا النطاق.'});const o=await Offer.create({nameAr:safeText(p.nameAr,160),discountType:type,discountValue:value,scope,targetProduct,targetCategory,targetMerchant,startDate:start,endDate:end,minOrderAmount:Math.max(0,Number(p.minOrderAmount)||0),maxDiscountAmount:p.maxDiscountAmount==null?null:Math.max(0,Number(p.maxDiscountAmount)||0),isActive:true});return res.json({ok:true,type:a.type,offer:{id:o._id,nameAr:o.nameAr},message:`تم إنشاء العرض «${o.nameAr}» بنجاح.`});}
 if(a.type==='create_coupon'){const type=p.discountType==='fixed'?'fixed':'percentage',value=Number(p.discountValue),days=Math.max(1,Math.min(Number(p.days)||7,365));if(!Number.isFinite(value)||value<=0||(type==='percentage'&&value>100))return res.status(400).json({message:'قيمة الخصم غير صالحة'});const start=new Date(),end=new Date(start.getTime()+days*86400000);try{const c=await Coupon.create({code:safeCode(p.code)||`MY-${crypto.randomBytes(3).toString('hex').toUpperCase()}`,titleAr:safeText(p.titleAr||`خصم ${value}%`,120),descriptionAr:'تم إنشاؤه بواسطة MYBRAND AI بعد تأكيد المدير.',discountType:type,discountValue:value,minOrderAmount:Math.max(0,Number(p.minOrderAmount)||0),usageLimit:p.usageLimit?Math.max(1,Number(p.usageLimit)):null,perUserLimit:Math.max(1,Number(p.perUserLimit)||1),startDate:start,endDate:end,isActive:true,rewardOnly:Boolean(p.rewardOnly)});return res.json({ok:true,type:a.type,coupon:{id:c._id,code:c.code,endDate:c.endDate},message:`تم إنشاء الكوبون ${c.code} بنجاح.`});}catch(e){if(e?.code===11000)return res.status(409).json({message:'رمز الكوبون مستخدم بالفعل.'});throw e;}}
 if(a.type==='update_product'){const product=p.productId?await Product.findById(p.productId):await Product.findOne({$or:[{nameAr:safeText(p.productName,180)},{nameEn:safeText(p.productName,180)}]});if(!product)return res.status(404).json({message:'لم أجد المنتج المحدد.'});const u={};['nameAr','descriptionAr','videoUrl','videoPoster','isFeatured','isActive','price','compareAtPrice','tags'].forEach(k=>{if(p[k]!==undefined)u[k]=p[k]});if(u.price!==undefined)u.price=Math.max(0,Number(u.price));if(u.compareAtPrice!==undefined)u.compareAtPrice=Math.max(0,Number(u.compareAtPrice));const updated=await Product.findByIdAndUpdate(product._id,u,{new:true,runValidators:true});return res.json({ok:true,type:a.type,product:updated,message:`تم تحديث المنتج «${updated.nameAr||updated.nameEn}» بنجاح.`});}
 if(a.type==='update_order_status'){if(!p.orderNumber||!orderStatuses.includes(p.status))return res.status(400).json({message:'رقم الطلب أو الحالة غير صالحة.'});const order=await Order.findOneAndUpdate({orderNumber:p.orderNumber},{status:p.status},{new:true});if(!order)return res.status(404).json({message:'لم أجد الطلب المحدد.'});return res.json({ok:true,type:a.type,order:{orderNumber:order.orderNumber,status:order.status},message:`تم تحديث الطلب ${order.orderNumber}.`});}
 if(a.type==='create_campaign'){const days=Math.max(1,Math.min(Number(p.days)||7,365)),start=new Date(),end=new Date(start.getTime()+days*86400000);const c=await Campaign.create({nameAr:safeText(p.nameAr,120),descriptionAr:safeText(p.descriptionAr,500),startDate:start,endDate:end,isActive:p.isActive!==false});return res.json({ok:true,type:a.type,campaign:{id:c._id,nameAr:c.nameAr},message:`تم إنشاء الحملة «${c.nameAr}».`});}
 if(a.type==='update_banner'){const banner=p.bannerId?await Banner.findById(p.bannerId):await Banner.findOne({titleAr:safeText(p.titleAr,180)});if(!banner)return res.status(404).json({message:'لم أجد البانر المحدد.'});const u={};['titleAr','subtitleAr','buttonTextAr','buttonLink','isActive','sortOrder'].forEach(k=>{if(p[k]!==undefined)u[k]=p[k]});const updated=await Banner.findByIdAndUpdate(banner._id,u,{new:true,runValidators:true});return res.json({ok:true,type:a.type,banner:updated,message:'تم تحديث البانر بنجاح.'});}
 return res.status(400).json({message:'نوع الإجراء غير متاح.'});
};
