const crypto = require('crypto');
const jwt = require('jsonwebtoken');
const nodemailer = require('nodemailer');
const User = require('../models/User');
const StaffMember = require('../models/StaffMember');
const { createVerificationCode, hashVerificationCode, sendVerificationCode, verificationExpiry } = require('../utils/emailVerification');

const MIN_PASSWORD_LENGTH = 12;
const signToken = (id) => jwt.sign({ id }, process.env.JWT_SECRET, { expiresIn: process.env.JWT_EXPIRES_IN || '7d' });
const normalizeEmail = (email) => String(email || '').trim().toLowerCase();
const normalizePhone = (phone) => {
  let value = String(phone || '').trim().replace(/\s+/g, '').replace(/[()-]/g, '');
  if (value.startsWith('00')) value = `+${value.slice(2)}`;
  if (value.startsWith('+20')) value = `0${value.slice(3)}`;
  else if (/^20\d{10}$/.test(value)) value = `0${value.slice(2)}`;
  else if (/^1\d{9}$/.test(value)) value = `0${value}`;
  return value;
};
const normalizeStoredPhone = (phone) => normalizePhone(phone);
const phoneCandidates = (phone) => { const raw = String(phone || '').trim(); const normalized = normalizePhone(raw); const stored = normalizeStoredPhone(raw); return [...new Set([raw, normalized, stored].filter(Boolean))]; };
const userPayload = (user, staff) => ({
  id: user._id, name: user.name, email: user.email, role: user.role, country: user.country,
  governorate: user.governorate, center: user.center,
  ...(user.role === 'staff' && staff ? { staffRole: staff.role, staffPermissions: staff.permissions || {} } : {}),
});
const getMailer = () => { const host = process.env.SMTP_HOST, user = process.env.SMTP_USER, pass = process.env.SMTP_PASS; if (!host || !user || !pass || user.includes('YOUR_') || pass.includes('YOUR_')) return null; return nodemailer.createTransport({ host, port: Number(process.env.SMTP_PORT) || 587, secure: String(process.env.SMTP_SECURE).toLowerCase() === 'true', auth: { user, pass } }); };

exports.register = async (req, res, next) => { try {
  const { name, country, governorate, center } = req.body; const email = normalizeEmail(req.body.email); const phone = normalizeStoredPhone(req.body.phone); const password = String(req.body.password || ''); const normalizedCountry = String(country || '').trim();
  const requiresEgyptLocation = normalizedCountry === 'مصر';
  if (!name || !email || !password || !phone || !normalizedCountry || (requiresEgyptLocation && (!governorate || !center))) return res.status(400).json({ message: requiresEgyptLocation ? 'يرجى إدخال جميع البيانات المطلوبة واختيار البلد والمحافظة والمركز' : 'يرجى إدخال جميع البيانات المطلوبة واختيار البلد' });
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return res.status(400).json({ message: 'يرجى إدخال بريد إلكتروني صحيح' });
  if (password.length < MIN_PASSWORD_LENGTH) return res.status(400).json({ message: `كلمة المرور يجب أن تكون ${MIN_PASSWORD_LENGTH} حرفًا على الأقل` });
  const [phoneExists, emailExists] = await Promise.all([User.findOne({ phone: { $in: phoneCandidates(phone) } }).select('_id'), User.findOne({ email }).select('_id')]);
  if (phoneExists) return res.status(409).json({ message: 'رقم الموبايل مستخدم بالفعل' }); if (emailExists) return res.status(409).json({ message: 'البريد الإلكتروني مستخدم بالفعل' });
  const verificationCode = createVerificationCode(); try { await sendVerificationCode(email, verificationCode); } catch (mailError) { if (mailError?.code === 'SMTP_NOT_CONFIGURED') return res.status(503).json({ message: 'تأكيد البريد الإلكتروني غير مهيأ حاليًا. أضف إعدادات SMTP أولًا.' }); throw mailError; }
  let user; try { user = await User.create({ name: String(name).trim(), phone, email, country: normalizedCountry, governorate: governorate || '', center: center || '', password, isEmailVerified: false, emailVerificationCode: hashVerificationCode(verificationCode), emailVerificationExpires: verificationExpiry() }); } catch (err) { if (err?.code === 11000 && err?.keyPattern?.phone) return res.status(409).json({ message: 'رقم الموبايل مستخدم بالفعل' }); if (err?.code === 11000 && err?.keyPattern?.email) return res.status(409).json({ message: 'البريد الإلكتروني مستخدم بالفعل' }); throw err; }
  return res.status(201).json({ user: userPayload(user), needsVerification: true, email: user.email, message: 'تم إنشاء الحساب. أرسلنا كود تأكيد إلى بريدك الإلكتروني.' });
} catch (err) { next(err); } };

exports.verifyEmail = async (req, res, next) => { try { const email = normalizeEmail(req.body.email); const code = String(req.body.code || '').replace(/\D/g, '').slice(0, 6); if (!email || code.length !== 6) return res.status(400).json({ message: 'يرجى إدخال البريد الإلكتروني والكود المكوّن من 6 أرقام' }); const user = await User.findOne({ email }).select('+emailVerificationCode +emailVerificationExpires +password'); if (!user) return res.status(404).json({ message: 'الحساب غير موجود' }); if (user.isEmailVerified) { const staff = user.role === 'staff' ? await StaffMember.findOne({ email: user.email, isActive: true }).lean() : null; return res.json({ token: signToken(user._id), user: userPayload(user, staff), message: 'البريد الإلكتروني مؤكد بالفعل' }); } if (!user.emailVerificationExpires || user.emailVerificationExpires <= new Date()) return res.status(410).json({ message: 'انتهت صلاحية كود التحقق. اطلب كودًا جديدًا.' }); const expected = Buffer.from(hashVerificationCode(code)); const actual = Buffer.from(user.emailVerificationCode || ''); if (actual.length !== expected.length || !crypto.timingSafeEqual(actual, expected)) return res.status(400).json({ message: 'كود التحقق غير صحيح' }); user.isEmailVerified = true; user.emailVerificationCode = undefined; user.emailVerificationExpires = undefined; await user.save({ validateBeforeSave: false }); const staff = user.role === 'staff' ? await StaffMember.findOne({ email: user.email, isActive: true }).lean() : null; res.json({ token: signToken(user._id), user: userPayload(user, staff), message: 'تم تأكيد البريد الإلكتروني بنجاح' }); } catch (err) { next(err); } };
exports.resendVerificationCode = async (req, res, next) => { try { const email = normalizeEmail(req.body.email); if (!email) return res.status(400).json({ message: 'يرجى إدخال البريد الإلكتروني' }); const user = await User.findOne({ email }).select('+emailVerificationCode +emailVerificationExpires'); if (!user) return res.status(404).json({ message: 'الحساب غير موجود' }); if (user.isEmailVerified) return res.status(409).json({ message: 'البريد الإلكتروني مؤكد بالفعل. يمكنك تسجيل الدخول.' }); const code = createVerificationCode(); try { await sendVerificationCode(email, code); } catch (mailError) { if (mailError?.code === 'SMTP_NOT_CONFIGURED') return res.status(503).json({ message: 'خدمة البريد الإلكتروني غير مهيأة حاليًا.' }); throw mailError; } user.emailVerificationCode = hashVerificationCode(code); user.emailVerificationExpires = verificationExpiry(); await user.save({ validateBeforeSave: false }); res.json({ message: 'تم إرسال كود تحقق جديد إلى بريدك الإلكتروني.' }); } catch (err) { next(err); } };
exports.forgotPassword = async (req, res, next) => { const generic = 'إذا كان الحساب موجودًا، فسيتم إرسال تعليمات استعادة كلمة المرور إلى البريد الإلكتروني المرتبط به.'; try { const email = normalizeEmail(req.body.email); if (!email) return res.status(400).json({ message: 'يرجى إدخال البريد الإلكتروني' }); const user = await User.findOne({ email }).select('+passwordResetTokenHash +passwordResetExpires'); if (!user || !user.isActive) return res.status(200).json({ message: generic }); const rawToken = crypto.randomBytes(32).toString('hex'); user.passwordResetTokenHash = crypto.createHash('sha256').update(rawToken).digest('hex'); user.passwordResetExpires = new Date(Date.now() + 15 * 60 * 1000); await user.save({ validateBeforeSave: false }); const mailer = getMailer(); if (!mailer) { user.passwordResetTokenHash = undefined; user.passwordResetExpires = undefined; await user.save({ validateBeforeSave: false }); return res.status(503).json({ message: 'خدمة استعادة كلمة المرور بالبريد الإلكتروني غير مهيأة حاليًا.' }); } const publicUrl = String(process.env.PUBLIC_STORE_URL || '').replace(/\/$/, ''); const resetUrl = `${publicUrl}/reset-password?token=${encodeURIComponent(rawToken)}`; await mailer.sendMail({ from: process.env.SMTP_FROM || process.env.SMTP_USER, to: user.email, subject: 'MYBRAND — استعادة كلمة المرور', text: `لإعادة تعيين كلمة المرور افتح الرابط التالي خلال 15 دقيقة:\n${resetUrl}\n\nإذا لم تطلب ذلك، تجاهل هذه الرسالة.` }); return res.status(200).json({ message: generic }); } catch (err) { next(err); } };
exports.resetPassword = async (req, res, next) => { try { const { token } = req.body; const password = String(req.body.password || ''); if (!token || !password) return res.status(400).json({ message: 'بيانات إعادة التعيين غير مكتملة' }); if (password.length < MIN_PASSWORD_LENGTH) return res.status(400).json({ message: `كلمة المرور يجب أن تكون ${MIN_PASSWORD_LENGTH} حرفًا على الأقل` }); const tokenHash = crypto.createHash('sha256').update(String(token)).digest('hex'); const user = await User.findOne({ passwordResetTokenHash: tokenHash, passwordResetExpires: { $gt: new Date() } }).select('+password'); if (!user) return res.status(400).json({ message: 'رابط إعادة التعيين غير صالح أو انتهت صلاحيته' }); user.password = password; user.passwordResetTokenHash = undefined; user.passwordResetExpires = undefined; await user.save(); return res.json({ message: 'تم تغيير كلمة المرور بنجاح. يمكنك تسجيل الدخول الآن.' }); } catch (err) { next(err); } };
exports.login = async (req, res, next) => { try { const email = normalizeEmail(req.body.email); const password = String(req.body.password || ''); if (!email || !password || !email.includes('@')) return res.status(400).json({ message: 'يرجى إدخال البريد الإلكتروني وكلمة المرور' }); const user = await User.findOne({ email }).select('+password'); if (!user || !(await user.comparePassword(password))) return res.status(401).json({ message: 'البريد الإلكتروني أو كلمة المرور غير صحيحة' }); if (!user.isActive) return res.status(403).json({ message: 'هذا الحساب معطّل' }); if (user.email && !user.isEmailVerified) return res.status(403).json({ message: 'يرجى تأكيد البريد الإلكتروني أولًا', needsVerification: true, email: user.email }); const staff = user.role === 'staff' ? await StaffMember.findOne({ email: user.email, isActive: true }).lean() : null; if (user.role === 'staff' && !staff) return res.status(403).json({ message: 'حساب الموظف غير مفعّل أو غير مسجل ضمن الفريق' }); const token = signToken(user._id); res.json({ token, user: userPayload(user, staff) }); } catch (err) { next(err); } };
exports.logout = async (req, res) => res.json({ message: 'تم تسجيل الخروج بنجاح' });
exports.getMe = async (req, res) => res.json({ user: userPayload(req.user, req.staff) });
