const ChatConversation=require('../models/ChatConversation');
const Order=require('../models/Order');
const ReturnRequest=require('../models/ReturnRequest');
const text=(v,max=2000)=>String(v??'').trim().slice(0,max);
const normalizeVisitorId=v=>text(v,120).replace(/[^a-zA-Z0-9._:-]/g,'');
const labels={shipping:'مشكلة في الشحن',payment:'مشكلة في الدفع',return:'الإرجاع',exchange:'الاستبدال',complaint:'شكوى أو مشكلة'};
const serviceTypes=Object.keys(labels);
const detectService=s=>{if(/إرجاع|ارجاع/.test(s))return'return';if(/استبدال/.test(s))return'exchange';if(/شحن|شحنة|توصيل|مندوب|متأخر|لم تصل|ماوصلتش|لم يصل/.test(s))return'shipping';if(/دفع|دفعت|خصم|بطاقة|عملية الدفع/.test(s))return'payment';if(/شكوى|مشكلة|عقبة|خطأ|سيئ|سيء/.test(s))return'complaint';return null};
const getOrCreate=async(visitorId,userId=null)=>{let convo=await ChatConversation.findOne({visitorId,status:{$ne:'closed'}});if(!convo)convo=await ChatConversation.create({visitorId,user:userId||null,messages:[{role:'assistant',text:'أهلاً بك في MYBRAND CARE 💛\nأنا مساعد خدمة العملاء. أنا مخصص للمشاكل والعقبات بعد أو أثناء الطلب: الشحن، الإرجاع والاستبدال، الدفع والشكاوى، وأحوّلك لموظف عند الحاجة.'}]});else if(userId&&!convo.user){convo.user=userId;await convo.save()}return convo};
const mergeService=(convo,incoming={})=>{const old=convo.serviceDraft?.toObject?.()||convo.serviceDraft||{};convo.serviceDraft={...old,type:serviceTypes.includes(incoming.type)?incoming.type:(old.type||null),orderId:incoming.orderId||old.orderId||null,orderNumber:incoming.orderNumber!=null?text(incoming.orderNumber,100):(old.orderNumber||''),reason:incoming.reason!=null?text(incoming.reason,1200):(old.reason||''),note:incoming.note!=null?text(incoming.note,1500):(old.note||''),ready:incoming.ready===true};return convo.serviceDraft};
const findOrder=async(convo,number)=>{if(!convo.user)return null;const value=text(number,100);if(!value)return null;const byNumber=await Order.findOne({orderNumber:value,user:convo.user});if(byNumber)return byNumber;if(/^[a-f\d]{24}$/i.test(value))return Order.findOne({_id:value,user:convo.user});return null};
const firstPrompt=type=>({return:'تمام. اكتب رقم الطلب وسبب الإرجاع.',exchange:'تمام. اكتب رقم الطلب وسبب الاستبدال.',shipping:'تمام. اكتب رقم الطلب واشرح مشكلة الشحن أو التوصيل.',payment:'تمام. اكتب رقم الطلب إن وجد واشرح مشكلة الدفع أو الخصم.',complaint:'تمام. اشرح المشكلة بالتفصيل، واكتب رقم الطلب إن كانت مرتبطة بطلب.'}[type]);

exports.getConversation=async(req,res)=>{try{const visitorId=normalizeVisitorId(req.params.visitorId||req.query.visitorId);if(!visitorId)return res.status(400).json({message:'visitorId مطلوب'});const convo=await getOrCreate(visitorId,req.user?._id);return res.json({conversation:convo,serviceDraft:convo.serviceDraft})}catch(e){console.error(e);return res.status(500).json({message:'تعذر تحميل المحادثة.'})}};

exports.sendMessage=async(req,res)=>{try{const visitorId=normalizeVisitorId(req.body?.visitorId),message=text(req.body?.message);if(!visitorId||!message)return res.status(400).json({message:'visitorId والرسالة مطلوبان'});const convo=await getOrCreate(visitorId,req.user?._id);mergeService(convo,req.body?.serviceDraft||{});convo.messages.push({role:'customer',text:message});convo.lastMessageAt=new Date();const lower=message.toLocaleLowerCase('ar-EG');const sd=convo.serviceDraft;
if(req.body?.serviceDraft?.ready===true&&serviceTypes.includes(sd.type)){
 if(!convo.user){sd.ready=false;convo.messages.push({role:'assistant',text:'لإتمام خدمة الطلب، سجّل الدخول أولًا حتى أتحقق من الطلب وأحافظ على أمان حسابك.'});}
 else if(sd.type==='return'||sd.type==='exchange'){
  const order=await findOrder(convo,sd.orderNumber);if(!order){sd.ready=false;convo.messages.push({role:'assistant',text:'لم أجد الطلب بهذا الرقم في حسابك. راجع الرقم وأرسله مرة أخرى.'});}
  else if(!['confirmed','processing','shipped','delivered'].includes(order.status)){sd.ready=false;convo.messages.push({role:'assistant',text:'لا يمكن إنشاء طلب الإرجاع أو الاستبدال لهذا الطلب في حالته الحالية.'});}
  else{const existing=await ReturnRequest.findOne({order:order._id,user:convo.user,status:{$nin:['rejected','completed']}});if(existing){sd.orderId=order._id;sd.ready=false;convo.status='waiting_agent';convo.messages.push({role:'assistant',text:`يوجد بالفعل طلب ${existing.type==='exchange'?'استبدال':'إرجاع'} مفتوح لهذا الطلب. أحلت الحالة للموظف لمتابعتها معك.`});}else{const rr=await ReturnRequest.create({order:order._id,user:convo.user,reason:sd.reason,note:sd.note,type:sd.type});sd.orderId=order._id;sd.ready=false;convo.status='waiting_agent';convo.messages.push({role:'assistant',text:`تم تسجيل طلب ${sd.type==='exchange'?'الاستبدال':'الإرجاع'} ✅\nرقم الطلب: ${order.orderNumber}\nرقم متابعة الخدمة: ${rr._id}\nوسيواصل موظف خدمة العملاء معك من نفس الشات.`});}}
 }else if(sd.type==='shipping'){
  const order=await findOrder(convo,sd.orderNumber);if(!order){sd.ready=false;convo.messages.push({role:'assistant',text:'لم أجد الطلب بهذا الرقم. أرسله مرة أخرى للتحقق من الشحنة.'});}else{sd.orderId=order._id;sd.ready=false;convo.status='waiting_agent';convo.messages.push({role:'assistant',text:`تم العثور على طلبك ✅\nالحالة الحالية: ${order.status||'غير محددة'}${order.trackingNumber?`\nرقم التتبع: ${order.trackingNumber}`:''}\nتم إرسال مشكلة الشحن لخدمة العملاء للمتابعة.`});}
 }else{sd.ready=false;convo.status='waiting_agent';convo.messages.push({role:'assistant',text:`تم تسجيل ${labels[sd.type]} ✅\nتم إرسال التفاصيل لخدمة العملاء، وسيكمل معك الموظف من نفس الشات.`});}
}else if(/موظف|خدمة العملاء|خدمه العملاء|شخص/.test(lower)){convo.status='waiting_agent';convo.messages.push({role:'assistant',text:'تم تحويل المحادثة إلى موظف خدمة العملاء 👨‍💼 وسيكمل معك من نفس الشات.'});}
else{
 const service=detectService(lower);
 if(service){sd.type=service;sd.ready=false;convo.messages.push({role:'assistant',text:firstPrompt(service)});}
 else if(sd.type&&serviceTypes.includes(sd.type)){
  if(!sd.orderNumber&&/^(?:بدون طلب|لا يوجد|مفيش|مافيش)$/i.test(lower)){sd.ready=false;sd.reason='بلاغ عام بدون رقم طلب';convo.status='waiting_agent';convo.messages.push({role:'assistant',text:'تم تسجيل البلاغ بدون رقم طلب ✅ وأرسلته لخدمة العملاء.'});}
  else if(!sd.orderNumber&&/(?:MB[- ]?\d{3,}|\d{5,})/i.test(message)){sd.orderNumber=(message.match(/(?:MB[- ]?\d{3,}|\d{5,})/i)||[''])[0];convo.messages.push({role:'assistant',text:'تم تسجيل رقم الطلب ✅ الآن اشرح المشكلة بالتفصيل.'});}
  else if(!sd.reason){sd.reason=message;convo.messages.push({role:'assistant',text:'تم حفظ تفاصيل المشكلة ✅ راجع بيانات الخدمة في الشات ثم اضغط «تنفيذ طلب الخدمة».'});}
  else convo.messages.push({role:'assistant',text:'تم حفظ التفاصيل. يمكنك تنفيذ طلب الخدمة أو طلب موظف خدمة العملاء.'});
 }
 else convo.messages.push({role:'assistant',text:'أنا مخصص لخدمة العملاء فقط. اكتب مشكلتك مثل: تأخر الشحنة، إرجاع، استبدال، مشكلة في الدفع، أو شكوى، وسأتابعها معك من هنا.'});
}
await convo.save();return res.json({conversation:convo,status:convo.status,serviceDraft:convo.serviceDraft});}catch(e){console.error(e);return res.status(500).json({message:'تعذر إرسال الرسالة.'})}};

exports.requestAgent=async(req,res)=>{try{const visitorId=normalizeVisitorId(req.body?.visitorId);if(!visitorId)return res.status(400).json({message:'visitorId مطلوب'});const convo=await getOrCreate(visitorId,req.user?._id);mergeService(convo,req.body?.serviceDraft||{});convo.status='waiting_agent';convo.messages.push({role:'system',text:'العميل طلب موظف خدمة العملاء.'});convo.messages.push({role:'assistant',text:'تم طلب موظف خدمة العملاء 👨‍💼 وسنكمل المحادثة هنا.'});convo.lastMessageAt=new Date();await convo.save();return res.json({conversation:convo,serviceDraft:convo.serviceDraft})}catch(e){console.error(e);return res.status(500).json({message:'تعذر تحويل المحادثة.'})}};
exports.listAdminConversations=async(req,res)=>{try{const status=text(req.query.status,30);const query=status?{status}:{status:{$in:['waiting_agent','agent']}};const conversations=await ChatConversation.find(query).sort({lastMessageAt:-1,updatedAt:-1}).limit(100).populate('user','name email phone').lean();return res.json({conversations})}catch(e){console.error(e);return res.status(500).json({message:'تعذر تحميل محادثات العملاء.'})}};
exports.getAdminConversation=async(req,res)=>{try{const conversation=await ChatConversation.findById(req.params.id).populate('user','name email phone').lean();if(!conversation)return res.status(404).json({message:'المحادثة غير موجودة'});return res.json({conversation})}catch(e){return res.status(500).json({message:'تعذر تحميل المحادثة.'})}};
exports.agentReply=async(req,res)=>{try{const message=text(req.body?.message);if(!message)return res.status(400).json({message:'الرسالة مطلوبة'});const conversation=await ChatConversation.findById(req.params.id);if(!conversation)return res.status(404).json({message:'المحادثة غير موجودة'});conversation.status='agent';conversation.messages.push({role:'agent',text:message});conversation.lastMessageAt=new Date();await conversation.save();return res.json({conversation})}catch(e){console.error(e);return res.status(500).json({message:'تعذر إرسال رد الموظف.'})}};
exports.closeConversation=async(req,res)=>{try{const conversation=await ChatConversation.findById(req.params.id);if(!conversation)return res.status(404).json({message:'المحادثة غير موجودة'});conversation.status='closed';conversation.messages.push({role:'system',text:'تم إغلاق المحادثة بواسطة موظف خدمة العملاء.'});conversation.lastMessageAt=new Date();await conversation.save();return res.json({conversation})}catch(e){return res.status(500).json({message:'تعذر إغلاق المحادثة.'})}};
