const jwt = require('jsonwebtoken');
const User = require('../models/User');
const Merchant = require('../models/Merchant');
const Product = require('../models/Product');
const Order = require('../models/Order');
const { createVerificationCode, hashVerificationCode, sendVerificationCode, verificationExpiry } = require('../utils/emailVerification');

const normalizePhone = (phone) => { let value = String(phone || '').replace(/\s+/g, '').replace(/[()-]/g, ''); value = value.replace(/^\+20/, '').replace(/^0020/, '').replace(/^0/, ''); return value ? `0${value}` : ''; };
const phoneCandidates = (phone) => { const raw = String(phone || '').trim(); const normalized = normalizePhone(raw); const withoutZero = normalized.replace(/^0/, ''); return [...new Set([raw, normalized, withoutZero, `+20${withoutZero}`, `0020${withoutZero}`].filter(Boolean))]; };
const userPayload = (user) => ({ id: user._id, name: user.name, email: user.email, role: user.role, governorate: user.governorate, center: user.center });

exports.registerMerchant = async (req, res, next) => { try { const { name, password, governorate, center, businessName, storeName, businessPhone, businessDescription, businessAddress } = req.body; const email = String(req.body.email || '').trim().toLowerCase(); const phone = normalizePhone(req.body.phone); if (!name || !email || !password || !phone || !governorate || !center || !businessName || !storeName) return res.status(400).json({ message: 'يرجى اختيار المحافظة والمركز وإدخال جميع البيانات المطلوبة' }); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return res.status(400).json({ message: 'يرجى إدخال بريد إلكتروني صحيح' }); if (String(password).length < 6) return res.status(400).json({ message: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل' }); const [existingEmail, existingPhone] = await Promise.all([User.findOne({ email }).select('_id'), User.findOne({ phone: { $in: phoneCandidates(phone) } }).select('_id')]); if (existingEmail) return res.status(409).json({ message: 'البريد الإلكتروني مستخدم بالفعل' }); if (existingPhone) return res.status(409).json({ message: 'رقم الموبايل مستخدم بالفعل' }); const verificationCode = createVerificationCode(); try { await sendVerificationCode(email, verificationCode); } catch (mailError) { if (mailError?.code === 'SMTP_NOT_CONFIGURED') return res.status(503).json({ message: 'تأكيد البريد الإلكتروني غير مهيأ حاليًا. أضف إعدادات SMTP أولًا.' }); throw mailError; } const user = await User.create({ name: String(name).trim(), email, password, phone, governorate, center, role: 'merchant', isEmailVerified: false, emailVerificationCode: hashVerificationCode(verificationCode), emailVerificationExpires: verificationExpiry() }); const merchant = await Merchant.create({ user: user._id, businessName, storeName, businessPhone, businessDescription, businessAddress, governorate, center, status: 'pending' }); res.status(201).json({ user: userPayload(user), needsVerification: true, email: user.email, merchant, message: 'تم إنشاء طلب التاجر. أرسلنا كود تأكيد إلى بريدك الإلكتروني قبل تفعيل الحساب.' }); } catch (err) { next(err); } };
exports.getMyMerchantProfile = async (req, res, next) => { try { const stats = await computeMerchantStats(req.merchant._id); res.json({ merchant: req.merchant, stats }); } catch (err) { next(err); } };
exports.updateMyMerchantProfile = async (req, res, next) => { try { const { businessName, storeName, businessPhone, businessDescription, businessAddress, governorate, center } = req.body; const merchant = await Merchant.findByIdAndUpdate(req.merchant._id, { businessName, storeName, businessPhone, businessDescription, businessAddress, governorate, center }, { new: true, runValidators: true }); res.json({ merchant }); } catch (err) { next(err); } };
const computeMerchantStats = async (merchantId) => { const [productsCount, pendingProductsCount, salesAgg] = await Promise.all([Product.countDocuments({ merchant: merchantId }), Product.countDocuments({ merchant: merchantId, status: 'pending' }), Order.aggregate([{ $match: { status: { $ne: 'cancelled' } } }, { $unwind: '$items' }, { $match: { 'items.merchant': merchantId } }, { $group: { _id: null, ordersCount: { $addToSet: '$_id' }, totalSales: { $sum: '$items.lineTotal' }, totalCommission: { $sum: '$items.commissionAmount' }, totalMerchantAmount: { $sum: '$items.merchantAmount' } } }])]); const agg = salesAgg[0]; return { productsCount, pendingProductsCount, ordersCount: agg?.ordersCount?.length || 0, totalSales: agg?.totalSales || 0, totalCommission: agg?.totalCommission || 0, totalMerchantAmount: agg?.totalMerchantAmount || 0 }; };
exports.listMerchants = async (req, res, next) => { try { const { status } = req.query; const filter = status ? { status } : {}; const merchants = await Merchant.find(filter).populate('user', 'name email phone governorate center isActive isEmailVerified').sort('-createdAt'); res.json({ merchants }); } catch (err) { next(err); } };
exports.getMerchantOverview = async (req, res, next) => { try { const { status } = req.query; const merchantFilter = status ? { status } : {}; const [merchants, productAgg, salesAgg] = await Promise.all([Merchant.find(merchantFilter).populate('user', 'name email phone governorate center isActive isEmailVerified').sort('-createdAt').lean(), Product.aggregate([{ $group: { _id: '$merchant', productsCount: { $sum: 1 }, pendingProductsCount: { $sum: { $cond: [{ $eq: ['$status', 'pending'] }, 1, 0] } } } }]), Order.aggregate([{ $match: { status: { $ne: 'cancelled' } } }, { $unwind: '$items' }, { $match: { 'items.merchant': { $ne: null } } }, { $group: { _id: '$items.merchant', orders: { $addToSet: '$_id' }, totalSales: { $sum: '$items.lineTotal' }, totalCommission: { $sum: '$items.commissionAmount' }, totalMerchantAmount: { $sum: '$items.merchantAmount' } } }])]); const productMap = new Map(productAgg.map(x => [String(x._id), x])); const salesMap = new Map(salesAgg.map(x => [String(x._id), x])); const rows = merchants.map(m => { const key = String(m._id); const p = productMap.get(key) || {}; const s = salesMap.get(key) || {}; return { ...m, stats: { productsCount: p.productsCount || 0, pendingProductsCount: p.pendingProductsCount || 0, ordersCount: s.orders?.length || 0, totalSales: s.totalSales || 0, totalCommission: s.totalCommission || 0, totalMerchantAmount: s.totalMerchantAmount || 0 } }; }); const summary = rows.reduce((a, m) => { a.total += 1; if (m.status === 'approved') a.approved += 1; if (m.status === 'pending') a.pending += 1; if (m.status === 'suspended') a.suspended += 1; a.products += m.stats.productsCount; a.pendingProducts += m.stats.pendingProductsCount; a.orders += m.stats.ordersCount; a.sales += m.stats.totalSales; a.commission += m.stats.totalCommission; a.merchantAmount += m.stats.totalMerchantAmount; return a; }, { total: 0, approved: 0, pending: 0, suspended: 0, products: 0, pendingProducts: 0, orders: 0, sales: 0, commission: 0, merchantAmount: 0 }); res.json({ merchants: rows, summary }); } catch (err) { next(err); } };
exports.getMerchantById = async (req, res, next) => { try { const merchant = await Merchant.findById(req.params.id).populate('user', 'name email phone governorate center isActive isEmailVerified'); if (!merchant) return res.status(404).json({ message: 'التاجر غير موجود' }); const stats = await computeMerchantStats(merchant._id); res.json({ merchant, stats }); } catch (err) { next(err); } };
exports.updateMerchantStatus = async (req, res, next) => { try { const { status, suspensionReason } = req.body; if (!['pending', 'approved', 'suspended'].includes(status)) return res.status(400).json({ message: 'حالة غير صالحة' }); const merchant = await Merchant.findById(req.params.id); if (!merchant) return res.status(404).json({ message: 'التاجر غير موجود' }); merchant.status = status; if (status === 'approved') { merchant.approvedAt = new Date(); merchant.suspensionReason = ''; merchant.suspendedAt = null; } else if (status === 'suspended') { merchant.suspendedAt = new Date(); merchant.suspensionReason = suspensionReason || ''; } else { merchant.suspensionReason = ''; merchant.suspendedAt = null; } await merchant.save(); res.json({ merchant }); } catch (err) { next(err); } };
exports.updateMerchantCommission = async (req, res, next) => { try { const { commissionRate } = req.body; if (typeof commissionRate !== 'number' || commissionRate < 0 || commissionRate > 100) return res.status(400).json({ message: 'نسبة العمولة يجب أن تكون رقمًا بين 0 و100' }); const merchant = await Merchant.findByIdAndUpdate(req.params.id, { commissionRate }, { new: true, runValidators: true }); if (!merchant) return res.status(404).json({ message: 'التاجر غير موجود' }); res.json({ merchant }); } catch (err) { next(err); } };
exports.updateMerchantSellerLevel = async (req, res, next) => { try { const { sellerLevel } = req.body; if (!['beginner', 'featured', 'five_star'].includes(sellerLevel)) return res.status(400).json({ message: 'تصنيف بائع غير صالح' }); const merchant = await Merchant.findByIdAndUpdate(req.params.id, { sellerLevel }, { new: true, runValidators: true }); if (!merchant) return res.status(404).json({ message: 'التاجر غير موجود' }); res.json({ merchant, message: 'تم حفظ تصنيف البائع بنجاح' }); } catch (err) { next(err); } };

exports.updateMerchantByAdmin = async (req, res, next) => { try { const allowed = ['businessName', 'storeName', 'businessPhone', 'businessDescription', 'businessAddress', 'governorate', 'center', 'sellerLevel', 'commissionRate']; const merchantPatch = {}; allowed.filter(k => Object.prototype.hasOwnProperty.call(req.body, k)).forEach(k => { merchantPatch[k] = req.body[k]; }); if (merchantPatch.commissionRate !== undefined) { const rate = Number(merchantPatch.commissionRate); if (!Number.isFinite(rate) || rate < 0 || rate > 100) return res.status(400).json({ message: 'نسبة العمولة يجب أن تكون رقمًا بين 0 و100' }); merchantPatch.commissionRate = rate; } if (merchantPatch.sellerLevel !== undefined && !['beginner', 'featured', 'five_star'].includes(merchantPatch.sellerLevel)) return res.status(400).json({ message: 'تصنيف بائع غير صالح' }); const merchant = await Merchant.findById(req.params.id); if (!merchant) return res.status(404).json({ message: 'التاجر غير موجود' }); Object.assign(merchant, merchantPatch); await merchant.save(); if (req.body.name !== undefined || req.body.email !== undefined || req.body.phone !== undefined) { const userPatch = {}; if (req.body.name !== undefined) userPatch.name = String(req.body.name).trim(); if (req.body.email !== undefined) userPatch.email = String(req.body.email).trim().toLowerCase(); if (req.body.phone !== undefined) userPatch.phone = normalizePhone(req.body.phone); await User.findByIdAndUpdate(merchant.user, userPatch, { new: true, runValidators: true }); } const updated = await Merchant.findById(merchant._id).populate('user', 'name email phone governorate center isActive isEmailVerified'); res.json({ merchant: updated, message: 'تم تحديث بيانات التاجر بنجاح' }); } catch (err) { next(err); } };

exports.deleteMerchant = async (req, res, next) => { try { const merchant = await Merchant.findById(req.params.id); if (!merchant) return res.status(404).json({ message: 'التاجر غير موجود' }); const merchantId = merchant._id; const userId = merchant.user; await Product.deleteMany({ merchant: merchantId }); await Merchant.deleteOne({ _id: merchantId }); if (userId) await User.deleteOne({ _id: userId, role: 'merchant' }); res.json({ message: 'تم حذف التاجر نهائيًا من قاعدة البيانات' }); } catch (err) { next(err); } };

exports.computeMerchantStats = computeMerchantStats;
