import React, { useEffect, useState } from 'react';
import api from '../api/client';
import ImageUploader from '../components/ImageUploader';
import AIActionButton from '../components/AIActionButton';
import { isValidBannerUrl, normalizeBannerUrl } from '../utils/bannerUrl';

const PLACEMENTS = [['home','الصفحة الرئيسية'],['products','صفحة المنتجات'],['product','صفحة المنتج'],['account','الصفحة الشخصية'],['categories','صفحة الأقسام'],['trend','الترند'],['new-arrivals','وصل حديثًا'],['offers','العروض'],['sale','السيل']];
const emptyForm = { titleAr:'', subtitleAr:'', image:'', buttonTextAr:'', buttonLink:'', sortOrder:0, placements:['home'] };

export default function BannersPage(){
 const [banners,setBanners]=useState([]),[form,setForm]=useState(emptyForm),[editingId,setEditingId]=useState(null),[error,setError]=useState(''),[showForm,setShowForm]=useState(false);
 const load=async()=>{const {data}=await api.get('/banners/all');setBanners(data.banners||[])};
 useEffect(()=>{load()},[]);
 useEffect(()=>{const onAI=e=>{const a=e.detail;if(!a||!['create_banner','update_banner'].includes(a.type))return;const p=a.params||{};setEditingId(a.type==='update_banner'?(p.bannerId||null):null);setForm(c=>({...c,titleAr:p.titleAr??c.titleAr,subtitleAr:p.subtitleAr??c.subtitleAr,image:p.image??c.image,buttonTextAr:p.buttonTextAr??c.buttonTextAr,buttonLink:p.buttonLink??c.buttonLink,sortOrder:p.sortOrder??c.sortOrder,placements:Array.isArray(p.placements)?p.placements:c.placements}));setShowForm(true)};window.addEventListener('mybrand-ai-prefill',onAI);return()=>window.removeEventListener('mybrand-ai-prefill',onAI)},[]);
 const handleChange=(field,value)=>setForm(f=>({...f,[field]:value}));
 const togglePlacement=value=>setForm(f=>({...f,placements:f.placements.includes(value)?f.placements.filter(p=>p!==value):[...f.placements,value]}));
 const handleSubmit=async e=>{e.preventDefault();setError('');if(!form.image)return setError('يرجى رفع صورة البانر');if(!form.placements.length)return setError('اختر صفحة واحدة على الأقل لظهور البانر');if(form.buttonLink&&!isValidBannerUrl(form.buttonLink))return setError('رابط الزر غير صالح');try{const payload={...form,buttonLink:normalizeBannerUrl(form.buttonLink),sortOrder:Number(form.sortOrder)||0};if(editingId)await api.put(`/banners/${editingId}`,payload);else await api.post('/banners',payload);setForm(emptyForm);setEditingId(null);setShowForm(false);load()}catch(err){setError(err?.response?.data?.message||'حدث خطأ')}};
 const handleEdit=b=>{setEditingId(b._id);setForm({titleAr:b.titleAr,subtitleAr:b.subtitleAr||'',image:b.image,buttonTextAr:b.buttonTextAr||'',buttonLink:b.buttonLink||'',sortOrder:b.sortOrder||0,placements:Array.isArray(b.placements)&&b.placements.length?b.placements:['home']});setShowForm(true)};
 const toggle=async id=>{await api.put(`/banners/${id}/toggle`);load()}; const remove=async id=>{if(!confirm('حذف هذا البانر؟'))return;await api.delete(`/banners/${id}`);load()}; const label=v=>PLACEMENTS.find(([k])=>k===v)?.[1]||v;
 return <div><div style={styles.headerRow}><div><h1>البنرات</h1><p style={{color:'#64748B',marginBottom:0,fontSize:13}}>أضف البنر وحدد الصفحات التي تريد ظهوره فيها.</p></div><div style={{display:'flex',gap:8}}><button style={styles.addBtn} onClick={()=>{setForm(emptyForm);setEditingId(null);setShowForm(s=>!s)}}>{showForm?'إلغاء':'+ إضافة بانر'}</button><AIActionButton prompt="أنشئ بانرًا جديدًا وحدد مكان ظهوره. جهّز الإجراء ولا تنفذه بدون تأكيد."/></div></div>
 {error&&<p style={{color:'#DC2626'}}>{error}</p>}
 {showForm&&<form onSubmit={handleSubmit} style={styles.form}><input style={styles.input} placeholder="العنوان الرئيسي" value={form.titleAr} onChange={e=>handleChange('titleAr',e.target.value)} required/><input style={styles.input} placeholder="نص فرعي (اختياري)" value={form.subtitleAr} onChange={e=>handleChange('subtitleAr',e.target.value)}/><ImageUploader images={form.image?[form.image]:[]} onChange={imgs=>handleChange('image',imgs[imgs.length-1]||'')}/>
 <div style={styles.placementBox}><div style={styles.placementTitle}>📍 مكان ظهور البنر <small>يمكن اختيار أكثر من صفحة</small></div><div style={styles.placementGrid}>{PLACEMENTS.map(([key,text])=><label key={key} style={{...styles.placementItem,...(form.placements.includes(key)?styles.placementSelected:{})}}><input type="checkbox" checked={form.placements.includes(key)} onChange={()=>togglePlacement(key)}/>{text}</label>)}</div></div>
 <div style={styles.row}><input style={styles.input} placeholder="نص الزر (اختياري)" value={form.buttonTextAr} onChange={e=>handleChange('buttonTextAr',e.target.value)}/><input style={styles.input} placeholder="رابط الزر" value={form.buttonLink} onChange={e=>handleChange('buttonLink',e.target.value)} dir="ltr"/></div><input style={styles.input} type="number" placeholder="ترتيب الظهور" value={form.sortOrder} onChange={e=>handleChange('sortOrder',e.target.value)}/><button style={styles.button} type="submit">{editingId?'حفظ التعديلات':'إضافة البانر'}</button></form>}
 <div style={styles.grid}>{banners.map(b=><div key={b._id} style={styles.card}><img src={b.image} alt="" style={styles.cardImage}/><div style={styles.cardBody}><p style={styles.cardName}>{b.titleAr}</p><p style={styles.cardSub}>{b.subtitleAr}</p><div style={styles.badgeWrap}>{(b.placements?.length?b.placements:['home']).map(p=><span key={p} style={styles.placementBadge}>{label(p)}</span>)}</div><div style={{display:'flex',gap:6,marginTop:8}}><span style={b.isActive?styles.activeBadge:styles.inactiveBadge}>{b.isActive?'مفعّل':'معطّل'}</span><span style={styles.orderBadge}>ترتيب: {b.sortOrder}</span></div><div style={{display:'flex',gap:6,marginTop:10}}><button style={styles.smallBtn} onClick={()=>toggle(b._id)}>{b.isActive?'تعطيل':'تفعيل'}</button><button style={styles.smallBtn} onClick={()=>handleEdit(b)}>تعديل</button><button style={{...styles.smallBtn,background:'#DC2626'}} onClick={()=>remove(b._id)}>حذف</button></div></div></div>)}</div></div>
}
const styles={headerRow:{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16},addBtn:{padding:'10px 18px',borderRadius:8,border:'none',background:'#0F172A',color:'#fff',cursor:'pointer'},form:{background:'#fff',padding:20,borderRadius:12,marginBottom:24,maxWidth:700},input:{width:'100%',padding:10,borderRadius:8,border:'1px solid #E2E8F0',marginBottom:12,boxSizing:'border-box'},row:{display:'flex',gap:12},placementBox:{border:'1px solid #E2E8F0',borderRadius:12,padding:14,marginBottom:12,background:'#F8FAFC'},placementTitle:{fontWeight:800,marginBottom:12,color:'#0F172A'},placementGrid:{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:8},placementItem:{display:'flex',alignItems:'center',gap:8,padding:'10px 12px',borderRadius:9,background:'#fff',border:'1px solid #E2E8F0',cursor:'pointer'},placementSelected:{borderColor:'#0F172A',boxShadow:'0 0 0 1px #0F172A'},button:{padding:'10px 20px',borderRadius:8,border:'none',background:'#0F172A',color:'#fff',cursor:'pointer'},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(240px,1fr))',gap:16},card:{background:'#fff',borderRadius:12,overflow:'hidden',boxShadow:'0 1px 4px rgba(0,0,0,.06)'},cardImage:{width:'100%',height:100,objectFit:'cover',display:'block'},cardBody:{padding:14},cardName:{fontWeight:700,margin:0,color:'#0F172A'},cardSub:{fontSize:12,color:'#64748B',margin:'4px 0'},badgeWrap:{display:'flex',flexWrap:'wrap',gap:5,marginTop:7},placementBadge:{padding:'3px 7px',borderRadius:999,background:'#EEF2FF',color:'#3730A3',fontSize:10,fontWeight:700},activeBadge:{padding:'2px 8px',borderRadius:999,background:'#DCFCE7',color:'#16A34A',fontSize:11},inactiveBadge:{padding:'2px 8px',borderRadius:999,background:'#F1F5F9',color:'#64748B',fontSize:11},orderBadge:{padding:'2px 8px',borderRadius:999,background:'#F1F5F9',color:'#64748B',fontSize:11},smallBtn:{padding:'4px 10px',borderRadius:6,border:'none',background:'#0F172A',color:'#fff',cursor:'pointer',fontSize:11}};
