import React,{useEffect,useState} from 'react';
import api from '../api/client';
import AIActionButton from '../components/AIActionButton';

const localInputValue=(date)=>{const d=new Date(date);const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`};
const toIso=(value)=>value?new Date(value).toISOString():value;
const initialForm=()=>{const now=new Date();const end=new Date(now.getTime()+30*24*60*60*1000);return {code:'',titleAr:'قسيمة خصم',descriptionAr:'',discountType:'percentage',discountValue:10,minOrderAmount:0,maxDiscountAmount:'',usageLimit:'',perUserLimit:1,startDate:localInputValue(now),endDate:localInputValue(end),isActive:true,rewardOnly:false};};

export default function CouponsPage(){
 const [coupons,setCoupons]=useState([]),[form,setForm]=useState(initialForm),[msg,setMsg]=useState('');
 const load=()=>api.get('/coupons').then(r=>setCoupons(r.data.coupons||[])); useEffect(()=>{load().catch(()=>setMsg('تعذر تحميل القسائم'))},[]);
 const change=(k,v)=>setForm(f=>({...f,[k]:v}));
 useEffect(()=>{const onPrefill=e=>{const p=e.detail?.params||{};setForm(f=>({...f,...Object.fromEntries(Object.entries(p).filter(([k])=>k in f).map(([k,v])=>[k,k==='startDate'||k==='endDate'?localInputValue(v):v]))}));setMsg('تم تجهيز بيانات الكوبون من MYBRAND AI. راجعها ثم اضغط إنشاء القسيمة.');};window.addEventListener('mybrand-ai-prefill',onPrefill);return()=>window.removeEventListener('mybrand-ai-prefill',onPrefill)},[]);
 const save=async e=>{e.preventDefault();setMsg('');try{await api.post('/coupons',{...form,startDate:toIso(form.startDate),endDate:toIso(form.endDate)});setMsg('تم إنشاء القسيمة وتفعيل مدتها حسب توقيتك المحلي');setForm(initialForm());load()}catch(err){setMsg(err.response?.data?.message||'تعذر إنشاء القسيمة')}};
 const remove=async id=>{if(!window.confirm('حذف القسيمة؟'))return;await api.delete(`/coupons/${id}`);load()};
 return <div dir="rtl" style={{padding:28,maxWidth:1200,margin:'auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,marginBottom:24}}><div><h1>الكوبونات والمكافآت</h1><p>أنشئ رموز الخصم، حدد شروطها، ووزع مكافآت خاصة للعملاء.</p></div><AIActionButton prompt="أنشئ كوبون خصم لمتجر MYBRAND. اسألني عن نسبة أو قيمة الخصم والمدة والحد الأدنى للطلب إذا كانت ناقصة، ويمكنك اقتراح رمز كوبون. جهّز الإجراء ولا تنفذه بدون تأكيد." /></div>{msg&&<div style={{padding:12,background:'#F8FAFC',borderRadius:10,marginBottom:15}}>{msg}</div>}<form onSubmit={save} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,padding:20,border:'1px solid #E2E8F0',borderRadius:18,marginBottom:25}}>{[['code','رمز القسيمة'],['titleAr','العنوان'],['descriptionAr','الوصف'],['discountValue','قيمة الخصم'],['minOrderAmount','الحد الأدنى للطلب'],['maxDiscountAmount','أقصى خصم'],['usageLimit','حد الاستخدام'],['perUserLimit','لكل عميل']].map(([k,l])=><label key={k}>{l}<input value={form[k]} onChange={e=>change(k,e.target.value)} required={k==='code'} style={{display:'block',width:'100%',padding:10,marginTop:5}}/></label>)}<label>نوع الخصم<select value={form.discountType} onChange={e=>change('discountType',e.target.value)} style={{display:'block',width:'100%',padding:10,marginTop:5}}><option value="percentage">نسبة مئوية</option><option value="fixed">مبلغ ثابت</option></select></label><label>البداية<input type="datetime-local" value={form.startDate} onChange={e=>change('startDate',e.target.value)} required style={{display:'block',width:'100%',padding:10,marginTop:5}}/></label><label>النهاية<input type="datetime-local" value={form.endDate} onChange={e=>change('endDate',e.target.value)} required style={{display:'block',width:'100%',padding:10,marginTop:5}}/></label><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={form.rewardOnly} onChange={e=>change('rewardOnly',e.target.checked)}/> مكافأة تُضاف للعميل</label><div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'center'}}><button type="submit" style={{padding:12,border:0,borderRadius:10,background:'#111827',color:'#fff',fontWeight:800}}>إنشاء القسيمة</button><AIActionButton label="اقتراح كوبون بـ AI" prompt="اقترح 3 كوبونات مناسبة لمتجر MYBRAND مع نسبة الخصم والمدة والرمز المقترح، ثم اسألني أي واحد أريد إنشاءه." /></div></form><div style={{display:'grid',gap:10}}>{coupons.map(c=><div key={c._id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:16,border:'1px solid #E2E8F0',borderRadius:14}}><div><b>{c.code}</b><div>{c.titleAr} — {c.discountType==='percentage'?`${c.discountValue}%`:`${c.discountValue} ج.م`} خصم</div><small>استخدام {c.usedCount}{c.usageLimit?` / ${c.usageLimit}`:''}</small></div><button onClick={()=>remove(c._id)} style={{border:0,color:'#B91C1C',background:'transparent'}}>حذف</button></div>)}</div></div>
}
