import React,{useEffect,useState}from'react';
import{Link,useParams}from'react-router-dom';
import{useAuth}from'../context/AuthContext';
import api from'../api/client';

const FEATURES={
 payments:{title:'وسائل الدفع',intro:'إدارة طرق الدفع تتم بأمان من خلال مسار الدفع في المتجر.',items:[['الدفع عند الطلب','اختر طريقة الدفع المتاحة عند الانتقال إلى إتمام الطلب.'],['حماية البيانات','لا تعرض الصفحة بيانات البطاقات أو رموز الدفع الحساسة.'],['إتمام الشراء','انتقل إلى صفحة إتمام الطلب لمراجعة الطريقة المتاحة قبل التأكيد.']],action:'/checkout',actionText:'الانتقال إلى الدفع'},
 history:{title:'سجل المشاهدة',intro:'هذه الصفحة جاهزة لعرض المنتجات التي شاهدتها عندما تتوفر بيانات السجل.',items:[['الخصوصية','سجل المشاهدة محلي على جهازك ولا يتم عرض بيانات مستخدم آخر.'],['التصفح','يمكنك العودة للرئيسية أو الأقسام لمتابعة التصفح.']],action:'/',actionText:'متابعة التسوق'},
 points:{title:'نقاط الولاء',intro:'رصيدك وحركاتك محفوظة في حسابك ويتم احتساب الاستبدال على الخادم وقت الطلب.',items:[],action:'/checkout',actionText:'استخدام النقاط في الشراء'},
 help:{title:'مركز المساعدة',intro:'مركز موحد لمساعدة العميل في الحساب والطلبات والدفع.',items:[['الطلبات','ابدأ من صفحة طلباتي لمراجعة الحالة ورقم الطلب.'],['الدفع','راجع صفحة إتمام الطلب قبل إعادة أي عملية دفع.'],['الحساب','يمكنك تعديل بيانات الحساب وتغيير كلمة المرور من الإعدادات.']],action:'/orders',actionText:'فتح طلباتي'},
 returns:{title:'الإرجاع والاستبدال',intro:'معلومات الإرجاع والاستبدال مرتبطة بسياسات المتجر والطلب.',items:[['قبل الإرجاع','راجع حالة الطلب وتفاصيله واحتفظ برقم الطلب.'],['المراجعة','تخضع طلبات الإرجاع والاستبدال لسياسة المتجر المعتمدة.'],['البيانات','لا يتم طلب أو عرض بيانات دفع حساسة لإتمام طلب الإرجاع.']],action:'/account/returns',actionText:'فتح طلبات الإرجاع'},
 contact:{title:'تواصل معنا',intro:'يمكنك الوصول إلى الدعم من خلال صفحة التواصل في المتجر.',items:[['الطلبات','أرسل رقم الطلب عند طلب المساعدة.'],['الحساب','لا ترسل كلمة المرور أو رمز استرجاع الحساب للدعم.'],['الأمان','لن يطلب فريق الدعم بيانات البطاقة السرية.']],action:'/contact',actionText:'فتح التواصل'},
 settings:{title:'إعدادات الحساب',intro:'تحكم في بيانات حسابك وكلمة المرور من خلال API المصادق عليه.',items:[]}
};

const txLabel={earn:'نقاط مكتسبة',redeem:'استبدال نقاط',adjust:'تعديل يدوي',reversal:'استرجاع نقاط'};

export default function AccountFeaturePage(){
 const{feature='settings'}=useParams();
 const{user}=useAuth();
 const cfg=FEATURES[feature]||FEATURES.settings;
 const[account,setAccount]=useState(null),[wallet,setWallet]=useState(null),[giftCards,setGiftCards]=useState([]),[giftBalance,setGiftBalance]=useState(0);
 const[form,setForm]=useState({name:'',phone:'',preferredLanguage:'ar'}),[pw,setPw]=useState({currentPassword:'',newPassword:''});
 const[code,setCode]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!user)return;api.get('/account').then(({data})=>{setAccount(data.user);setForm({name:data.user.name||'',phone:data.user.phone||'',preferredLanguage:data.user.preferredLanguage||'ar'});}).catch(()=>setMsg('تعذر تحميل بيانات الحساب'));if(feature==='points')api.get('/loyalty').then(({data})=>setWallet(data)).catch(()=>setMsg('تعذر تحميل نقاط الولاء'));if(feature==='gifts')api.get('/gift-cards/mine').then(({data})=>{setGiftCards(data.cards||[]);setGiftBalance(Number(data.giftBalance||0));}).catch(()=>setMsg('تعذر تحميل بطاقات الهدايا'));},[feature,user]);
 const saveProfile=async e=>{e.preventDefault();setBusy(true);setMsg('');try{const{data}=await api.put('/account/profile',form);setAccount(data.user);setMsg('تم حفظ بيانات الحساب بنجاح');}catch(e){setMsg(e.response?.data?.message||'تعذر حفظ البيانات')}finally{setBusy(false)}};
 const changePassword=async e=>{e.preventDefault();setBusy(true);setMsg('');try{await api.put('/account/password',pw);setPw({currentPassword:'',newPassword:''});setMsg('تم تغيير كلمة المرور بنجاح');}catch(e){setMsg(e.response?.data?.message||'تعذر تغيير كلمة المرور')}finally{setBusy(false)}};
 const redeem=async e=>{e.preventDefault();if(!code.trim())return;setBusy(true);setMsg('');try{const{data}=await api.post('/gift-cards/redeem',{code});setMsg(data.message||'تمت إضافة بطاقة الهدايا');setCode('');const mine=await api.get('/gift-cards/mine');setGiftCards(mine.data.cards||[]);setGiftBalance(Number(mine.data.giftBalance||0));}catch(e){setMsg(e.response?.data?.message||'تعذر إضافة بطاقة الهدايا')}finally{setBusy(false)}};
 if(!user)return <main dir="rtl" style={s.page}><div style={s.card}><Link to="/account" style={s.back}>← العودة إلى الحساب</Link><h1 style={s.h1}>سجّل الدخول أولًا</h1><p style={s.intro}>هذه الميزة متاحة لأعضاء MYBRAND المسجلين فقط.</p><Link to="/login" style={s.button}>تسجيل الدخول</Link></div></main>;
 return <main dir="rtl" style={s.page}><div style={s.card}><Link to="/account" style={s.back}>← العودة إلى الحساب</Link><h1 style={s.h1}>{cfg.title}</h1><p style={s.intro}>{feature==='gifts'?'أضف رمز بطاقة هدايا حصلت عليها، وسيتم ربطها بحسابك وحساب الرصيد المتاح تلقائيًا.':cfg.intro}</p>
 {feature==='gifts'?<><div style={s.giftHero}><span style={s.giftLabel}>رصيد بطاقات الهدايا</span><strong style={s.giftValue}>{giftBalance.toLocaleString('ar-EG')} ج.م</strong><small>الرصيد المرتبط بحسابك</small></div><form onSubmit={redeem} style={s.redeemForm}><h2 style={s.h2}>إضافة بطاقة جديدة</h2><input style={s.input} value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="أدخل رمز بطاقة الهدايا" autoComplete="off"/><button disabled={busy||!code.trim()} style={s.button}>{busy?'جارٍ التحقق...':'إضافة البطاقة'}</button></form><div style={s.history}><h2 style={s.h2}>بطاقاتك</h2>{giftCards.length?giftCards.map(c=><div key={c._id} style={s.tx}><div><b style={s.txTitle}>{c.code}</b><small style={s.txMeta}>{c.expiresAt?`صالحة حتى ${new Date(c.expiresAt).toLocaleDateString('ar-EG')}`:'بدون تاريخ انتهاء'}</small></div><strong>{Number(c.balance||0).toLocaleString('ar-EG')} ج.م</strong></div>):<p style={s.text}>لا توجد بطاقات هدايا مرتبطة بحسابك حتى الآن.</p>}</div><div style={s.note}>يمكن استخدام رصيد بطاقة الهدايا داخل المتجر عند توفره في مرحلة الدفع.</div></>:
 feature==='points'?<><div style={s.pointsHero}><div><span style={s.pointsLabel}>الرصيد المتاح</span><strong style={s.pointsValue}>{Number(wallet?.points||account?.points||0).toLocaleString('ar-EG')} نقطة</strong></div><small style={s.pointsNote}>{wallet?.config?.pointValue?`كل نقطة = ${wallet.config.pointValue} ج.م`:''}</small></div><div style={s.grid}><div style={s.item}><h2 style={s.h2}>طريقة الكسب</h2><p style={s.text}>{wallet?.config?`${wallet.config.pointsPer100} نقطة لكل 100 ج.م من صافي قيمة المشتريات المؤهلة.`:'جارٍ التحميل...'}</p></div><div style={s.item}><h2 style={s.h2}>الاستخدام</h2><p style={s.text}>{wallet?.config?`يمكن استخدام حتى ${wallet.config.maxRedeemPercent}% من قيمة المنتجات في الطلب.`:'جارٍ التحميل...'}</p></div></div><div style={s.history}><h2 style={s.h2}>آخر الحركات</h2>{wallet?.transactions?.length?wallet.transactions.map(tx=><div key={tx._id} style={s.tx}><div><b style={s.txTitle}>{txLabel[tx.type]||'حركة نقاط'}</b><small style={s.txMeta}>{tx.order?.orderNumber?`طلب ${tx.order.orderNumber}`:tx.reason||'حركة نقاط'}</small></div><strong style={{color:Number(tx.delta)>=0?'#16834d':'#d7263d'}}>{Number(tx.delta)>=0?'+':''}{Number(tx.delta).toLocaleString('ar-EG')}</strong></div>):<p style={s.text}>لا توجد حركات نقاط حتى الآن.</p>}</div><Link to={cfg.action} style={s.button}>{cfg.actionText}</Link></>:feature!=='settings'?<><div style={s.balance}>بيانات الحساب: <b>{account?.name||'عضو MYBRAND'}</b></div><div style={s.list}>{cfg.items.map(([h,t])=><section key={h} style={s.item}><h2 style={s.h2}>{h}</h2><p style={s.text}>{t}</p></section>)}</div><Link to={cfg.action} style={s.button}>{cfg.actionText}</Link></>:<><form onSubmit={saveProfile} style={s.form}><h2 style={s.h2}>بيانات الحساب</h2><label style={s.label}>الاسم<input style={s.input} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label style={s.label}>رقم الهاتف<input style={s.input} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label style={s.label}>اللغة<select style={s.input} value={form.preferredLanguage} onChange={e=>setForm({...form,preferredLanguage:e.target.value})}><option value="ar">العربية</option><option value="en">English</option></select></label><button disabled={busy} style={s.button}>{busy?'جارٍ الحفظ...':'حفظ بيانات الحساب'}</button></form><form onSubmit={changePassword} style={s.form}><h2 style={s.h2}>تغيير كلمة المرور</h2><label style={s.label}>كلمة المرور الحالية<input style={s.input} type="password" value={pw.currentPassword} onChange={e=>setPw({...pw,currentPassword:e.target.value})} required/></label><label style={s.label}>كلمة المرور الجديدة<input style={s.input} type="password" minLength={12} value={pw.newPassword} onChange={e=>setPw({...pw,newPassword:e.target.value})} required/></label><button disabled={busy} style={s.button}>تغيير كلمة المرور</button></form></>}{msg&&<div style={s.msg}>{msg}</div>}</div></main>}
const s={page:{minHeight:'100vh',background:'#f5f5f5',padding:'24px 16px 80px',fontFamily:'Tajawal,Arial,sans-serif'},card:{maxWidth:700,margin:'0 auto',background:'#fff',border:'1px solid #e5e7eb',borderRadius:18,padding:22,boxShadow:'0 10px 30px rgba(0,0,0,.06)'},back:{display:'inline-block',color:'#777',textDecoration:'none',fontSize:13,marginBottom:18},h1:{fontSize:25,margin:'0 0 8px',fontFamily:'Cairo,Arial,sans-serif'},intro:{color:'#64748b',lineHeight:1.9},balance:{margin:'18px 0',padding:12,borderRadius:12,background:'#fafafa'},giftHero:{margin:'18px 0',padding:20,borderRadius:16,background:'linear-gradient(135deg,#111,#ff6a00)',color:'#fff',display:'grid',gap:5},giftLabel:{fontSize:11,color:'#eee'},giftValue:{font:'900 30px Cairo,Arial'},pointsHero:{margin:'18px 0',padding:'18px',borderRadius:16,background:'linear-gradient(135deg,#171717,#303030)',color:'#fff',display:'flex',justifyContent:'space-between',alignItems:'center'},pointsLabel:{display:'block',fontSize:11,color:'#c7c7c7'},pointsValue:{display:'block',font:'900 28px Cairo,Arial',marginTop:5},pointsNote:{fontSize:11,color:'#d4b866'},grid:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10},list:{display:'grid',gap:10,margin:'18px 0'},item:{border:'1px solid #eee',borderRadius:12,padding:14},h2:{fontSize:16,margin:'0 0 7px',fontFamily:'Cairo,Arial,sans-serif'},text:{margin:0,color:'#475569',lineHeight:1.8},history:{marginTop:14,border:'1px solid #eee',borderRadius:14,padding:14},tx:{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'11px 0',borderBottom:'1px solid #f0f0f0'},txTitle:{display:'block',fontSize:12},txMeta:{display:'block',fontSize:10,color:'#777',marginTop:3},redeemForm:{display:'grid',gap:10,marginTop:18,padding:16,border:'1px solid #eee',borderRadius:14},label:{fontSize:12,fontWeight:700,color:'#334155'},form:{display:'grid',gap:12,marginTop:18,paddingTop:18,borderTop:'1px solid #eee'},input:{display:'block',width:'100%',marginTop:6,padding:11,border:'1px solid #dbe1e8',borderRadius:9,fontSize:13,background:'#fff'},button:{display:'inline-block',marginTop:8,padding:'11px 16px',borderRadius:10,border:0,background:'linear-gradient(100deg,#111,#ff6a00)',color:'#fff',fontWeight:800,textDecoration:'none',textAlign:'center',cursor:'pointer'},note:{marginTop:14,padding:12,borderRadius:12,background:'#fff7ed',color:'#9a3412',fontSize:11,lineHeight:1.7},msg:{marginTop:16,padding:11,borderRadius:10,background:'#111',color:'#fff',fontSize:12}};
