import React,{useEffect,useState}from'react';
import{Link}from'react-router-dom';
import{useAuth}from'../context/AuthContext';
import api from'../api/client';

const empty={label:'',fullName:'',phone:'',street:'',city:'',governorate:'',country:'مصر',postalCode:'',isDefault:false};
export default function AddressesPage(){const{user}=useAuth();const[items,setItems]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
const load=async()=>{setLoading(true);try{const r=await api.get('/account');setItems(r.data.user?.addresses||[])}catch(e){setMsg('تعذر تحميل العناوين')}finally{setLoading(false)}};
useEffect(()=>{if(!user){setLoading(false);return}load()},[user]);
const change=e=>setForm({...form,[e.target.name]:e.target.value});
const save=async e=>{e.preventDefault();setSaving(true);setMsg('');try{if(editing)await api.put(`/account/addresses/${editing}`,form);else await api.post('/account/addresses',form);setForm(empty);setEditing(null);await load()}catch(e){setMsg(e.response?.data?.message||'تعذر حفظ العنوان')}finally{setSaving(false)}};
const edit=a=>{setEditing(a._id);setForm({...empty,...a})};
const remove=async id=>{if(!window.confirm('هل تريد حذف هذا العنوان؟'))return;try{await api.delete(`/account/addresses/${id}`);await load()}catch(e){setMsg(e.response?.data?.message||'تعذر حذف العنوان')}};
const makeDefault=async id=>{try{await api.put(`/account/addresses/${id}`,{isDefault:true});await load()}catch(e){setMsg(e.response?.data?.message||'تعذر تعيين العنوان الافتراضي')}};
if(!user)return <main dir="rtl" style={S.page}><div style={S.card}><h1>العناوين المحفوظة</h1><p>سجّل الدخول لإدارة عناوين الشحن المحفوظة.</p><Link to="/login" style={S.primary}>تسجيل الدخول</Link></div></main>;
return <main dir="rtl" style={S.page}><header style={S.header}><h1>العناوين المحفوظة</h1><p>أضف عناوين الشحن وأدر العنوان الافتراضي لحسابك.</p></header>{msg&&<div style={S.msg}>{msg}</div>}<section style={S.card}><h2>{editing?'تعديل العنوان':'إضافة عنوان جديد'}</h2><form onSubmit={save} style={S.form}>{[['label','اسم العنوان'],['fullName','الاسم الكامل'],['phone','رقم الهاتف'],['street','العنوان بالتفصيل'],['city','المدينة'],['governorate','المحافظة'],['country','الدولة'],['postalCode','الرمز البريدي']].map(([name,label])=><label key={name}>{label}<input name={name} value={form[name]||''} onChange={change} required={['fullName','phone','street','city','country'].includes(name)}/></label>)}<label style={S.check}><input type="checkbox" checked={!!form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked})}/> اجعله العنوان الافتراضي</label><div><button disabled={saving} style={S.primary}>{saving?'جارٍ الحفظ…':editing?'حفظ التعديل':'حفظ العنوان'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}} style={S.secondary}>إلغاء</button>}</div></form></section><section style={S.list}><h2>عناويني</h2>{loading?<p>جارٍ التحميل…</p>:items.length===0?<p>لا توجد عناوين محفوظة بعد.</p>:items.map(a=><article key={a._id} style={S.item}><div><strong>{a.label||'عنوان الشحن'}</strong>{a.isDefault&&<span style={S.badge}>افتراضي</span>}<p>{a.fullName} — {a.phone}</p><p>{a.street}, {a.city}{a.governorate?`, ${a.governorate}`:''}{a.center?`, ${a.center}`:''}, {a.country}{a.postalCode?` — ${a.postalCode}`:''}</p></div><div style={S.actions}><button onClick={()=>edit(a)}>تعديل</button><button onClick={()=>remove(a._id)}>حذف</button>{!a.isDefault&&<button onClick={()=>makeDefault(a._id)}>جعله افتراضيًا</button>}</div></article>)}</section></main>}
const S={page:{minHeight:'100vh',background:'#f6f6f6',padding:'20px 14px 90px',fontFamily:'Tajawal,Arial,sans-serif',maxWidth:760,margin:'0 auto',color:'#111'},header:{marginBottom:16},card:{background:'#fff',border:'1px solid #e5e7eb',borderRadius:18,padding:18},list:{marginTop:14,background:'#fff',border:'1px solid #e5e7eb',borderRadius:18,padding:18},form:{display:'grid',gap:12},formLabel:{},item:{borderTop:'1px solid #eee',padding:'16px 0',display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start'},input:{},primary:{background:'#111',color:'#fff',border:0,borderRadius:10,padding:'11px 16px',cursor:'pointer'},secondary:{marginRight:8,border:'1px solid #ddd',background:'#fff',borderRadius:10,padding:'10px 16px'},actions:{display:'flex',gap:7,flexWrap:'wrap'},badge:{marginRight:8,background:'#eee',padding:'3px 8px',borderRadius:20,fontSize:11},check:{display:'flex',alignItems:'center',gap:8},msg:{background:'#111',color:'#fff',padding:10,borderRadius:10,marginBottom:12}};