import React,{useEffect,useState}from'react';
import{Link}from'react-router-dom';
import api from'../api/client';

export default function ReturnRequestsPage(){
 const[orders,setOrders]=useState([]),[requests,setRequests]=useState([]),[orderId,setOrderId]=useState(''),[type,setType]=useState('return'),[reason,setReason]=useState(''),[details,setDetails]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const load=async()=>{setLoading(true);try{const[o,r]=await Promise.all([api.get('/orders/my'),api.get('/returns/my')]);setOrders(o.data.orders||[]);setRequests(r.data.requests||r.data.returns||[])}catch(e){setMsg(e.response?.data?.message||'تعذر تحميل طلبات الإرجاع')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();if(!orderId||!reason)return;setBusy(true);setMsg('');try{await api.post('/returns',{orderId,type,reason,details});setMsg('تم إرسال طلب الإرجاع/الاستبدال بنجاح');setOrderId('');setReason('');setDetails('');await load()}catch(e){setMsg(e.response?.data?.message||'تعذر إرسال الطلب')}finally{setBusy(false)}};
 return <main dir="rtl" style={s.page}><div style={s.card}><Link to="/account" style={s.back}>← العودة إلى الحساب</Link><h1 style={s.h1}>الإرجاع والاستبدال</h1><p style={s.intro}>اختر طلبًا من طلباتك وأرسل طلب الإرجاع أو الاستبدال. ستظهر الحالة هنا بعد المراجعة.</p>
 {msg&&<div style={s.msg}>{msg}</div>}
 <form onSubmit={submit} style={s.form}><h2 style={s.h2}>طلب جديد</h2><label style={s.label}>الطلب<select required value={orderId} onChange={e=>setOrderId(e.target.value)} style={s.input}><option value="">اختر الطلب</option>{orders.map(o=><option key={o._id} value={o._id}>#{String(o._id).slice(-8)} — {o.total||o.totalAmount||0} ج.م</option>)}</select></label><label style={s.label}>نوع الطلب<select value={type} onChange={e=>setType(e.target.value)} style={s.input}><option value="return">إرجاع</option><option value="exchange">استبدال</option></select></label><label style={s.label}>السبب<textarea required value={reason} onChange={e=>setReason(e.target.value)} style={s.textarea} placeholder="اكتب سبب الإرجاع أو الاستبدال"/></label><label style={s.label}>تفاصيل إضافية<textarea value={details} onChange={e=>setDetails(e.target.value)} style={s.textarea}/></label><button disabled={busy||loading} style={s.button}>{busy?'جارٍ الإرسال...':'إرسال الطلب'}</button></form>
 <section style={s.list}><h2 style={s.h2}>طلباتي السابقة</h2>{loading?<p>جارٍ التحميل...</p>:requests.length===0?<p style={s.muted}>لا توجد طلبات إرجاع أو استبدال حتى الآن.</p>:requests.map(r=><article key={r._id} style={s.item}><b>{r.type==='exchange'?'استبدال':'إرجاع'}</b><span> الحالة: {r.status||'جديد'}</span><p>{r.reason}</p>{r.details&&<small>{r.details}</small>}</article>)}</section></div></main>}
const s={page:{minHeight:'100vh',background:'#f5f5f5',padding:'24px 16px 80px',fontFamily:'Tajawal,Arial,sans-serif'},card:{maxWidth:700,margin:'0 auto',background:'#fff',border:'1px solid #e5e7eb',borderRadius:18,padding:22},back:{display:'inline-block',color:'#777',textDecoration:'none',fontSize:13,marginBottom:18},h1:{fontSize:25,margin:'0 0 8px',fontFamily:'Cairo,Arial,sans-serif'},h2:{fontSize:17,margin:'0 0 12px',fontFamily:'Cairo,Arial,sans-serif'},intro:{color:'#64748b',lineHeight:1.9},form:{display:'grid',gap:12,marginTop:20},label:{fontSize:12,fontWeight:700,color:'#334155'},input:{display:'block',width:'100%',marginTop:6,padding:11,border:'1px solid #dbe1e8',borderRadius:9,fontSize:13,background:'#fff'},textarea:{display:'block',width:'100%',minHeight:90,marginTop:6,padding:11,border:'1px solid #dbe1e8',borderRadius:9,fontSize:13,resize:'vertical',boxSizing:'border-box'},button:{padding:'12px 16px',border:0,borderRadius:10,background:'linear-gradient(100deg,#ff3b30,#ff6a00)',color:'#fff',fontWeight:800,cursor:'pointer'},msg:{marginTop:14,padding:11,borderRadius:10,background:'#111',color:'#fff',fontSize:12},list:{marginTop:24,paddingTop:20,borderTop:'1px solid #eee'},item:{border:'1px solid #eee',borderRadius:12,padding:14,marginTop:10},muted:{color:'#64748b'}}