import React,{useEffect,useMemo,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {useWishlist} from '../context/WishlistContext';
import {useCart} from '../context/CartContext';
import api from '../api/client';
import './WishlistPage.css';

const CartIcon=({size=15})=><svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><circle cx="9" cy="21" r="1.4"/><circle cx="18" cy="21" r="1.4"/><path d="M3 4h2l2.4 11.4a2 2 0 0 0 2 1.6h7.2a2 2 0 0 0 2-1.6L21 8H6"/></svg>;
const Heart=()=> <svg width="14" height="14" viewBox="0 0 24 24" fill="var(--wish-red)" stroke="var(--wish-red)" strokeWidth="1"><path d="M20.8 4.6c-1.8-1.5-4.4-1.3-6 .4L12 7.8 9.2 5c-1.6-1.7-4.2-1.9-6-.4-2 1.7-2.1 4.8-.3 6.6L12 21l9.1-9.8c1.8-1.8 1.7-4.9-.3-6.6z"/></svg>;

const normalizeImage=(src)=>{if(!src)return '';if(/^https?:\/\//i.test(src)||src.startsWith('data:')||src.startsWith('blob:'))return src;return src.startsWith('/')?src:`/${src}`};

export default function WishlistPage(){
 const navigate=useNavigate(); const {productIds,toggleWishlist}=useWishlist(); const {addToCart}=useCart();
 const [catalog,setCatalog]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[sort,setSort]=useState('new');
 useEffect(()=>{let active=true;(async()=>{try{const {data}=await api.get('/products',{params:{limit:200}});if(active)setCatalog(Array.isArray(data?.products)?data.products:Array.isArray(data)?data:[])}catch(e){if(active)setError(e?.response?.data?.message||'تعذر تحميل المنتجات المحفوظة')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 const products=useMemo(()=>{const ids=new Set(productIds.map(String));const list=catalog.filter(p=>ids.has(String(p._id||p.id||p.productId)));return [...list].sort((a,b)=>sort==='price'?Number(a.price||0)-Number(b.price||0):sort==='name'?String(a.nameAr||a.name||'').localeCompare(String(b.nameAr||b.name||''),'ar'):new Date(b.createdAt||0)-new Date(a.createdAt||0))},[catalog,productIds,sort]);
 const clearAll=()=>productIds.forEach(id=>toggleWishlist(id));
 const add=(p)=>addToCart({id:p._id||p.id||p.productId,name:p.nameAr||p.name,price:Number(p.price||0),oldPrice:Number(p.compareAtPrice||0),image:normalizeImage(p.images?.[0]),color:'',size:'',store:p.merchant?.businessName||'MYBRAND'},1);
 if(loading)return <div className="wishlist-app" dir="rtl"><div className="wishlist-empty"><h1>المفضلة</h1><p>جارٍ تحميل المنتجات المحفوظة...</p></div></div>;
 if(!productIds.length||!products.length)return <div className="wishlist-app" dir="rtl"><div className="wishlist-empty"><Heart/><h1>المفضلة فارغة</h1><p>{error||'أضف المنتجات التي تعجبك لتجدها هنا.'}</p><Link to="/" className="wishlist-primary">تصفح المنتجات</Link></div></div>;
 return <div className="wishlist-app" dir="rtl"><header className="wishlist-topbar"><button type="button" className="back-btn" onClick={()=>navigate(-1)} aria-label="رجوع">‹</button><h1>المفضلة</h1><button type="button" className="edit-link" onClick={clearAll}>مسح الكل</button></header><div className="wishlist-tabs"><button type="button" className="wishlist-tab active">المنتجات <span className="count">({products.length})</span></button><Link to="/" className="wishlist-tab">متابعة التسوق</Link></div><div className="wishlist-count-row"><span>{products.length} منتجات محفوظة</span><select aria-label="ترتيب المنتجات" className="sort-btn" value={sort} onChange={e=>setSort(e.target.value)}><option value="new">الأحدث أولاً</option><option value="price">الأقل سعرًا</option><option value="name">الاسم</option></select></div>{error&&<div className="wishlist-hint">{error}</div>}<div className={`wishlist-grid ${products.length===1?'single':''}`}>{products.map(p=>{const id=p._id||p.id||p.productId;const out=Number(p.stock||0)<=0;const image=normalizeImage(p.images?.[0]);const path=p.slug||id;return <article className="wishlist-card" key={id}><Link to={`/products/${encodeURIComponent(path)}`} className={`wishlist-img ${out?'is-out':''}`}>{image?<img src={image} alt={p.nameAr||p.name||'منتج'} onError={e=>{e.currentTarget.style.display='none'}}/>:<div className="wishlist-placeholder"/>}<button type="button" className="fav-fill" onClick={e=>{e.preventDefault();e.stopPropagation();toggleWishlist(id)}} aria-label="إزالة من المفضلة"><Heart/></button>{out&&<span className="stock-flag">نفد المخزون</span>}</Link><div className="wishlist-info"><Link to={`/products/${encodeURIComponent(path)}`} className="wishlist-title">{p.nameAr||p.name}</Link><div className="price-line"><span className="price-now">{Number(p.price||0).toLocaleString('ar-EG')}ج</span>{Number(p.compareAtPrice||0)>Number(p.price||0)&&<span className="price-old">{Number(p.compareAtPrice).toLocaleString('ar-EG')}ج</span>}</div><button type="button" className={`add-cart-mini ${out?'dim':''}`} disabled={out} onClick={()=>add(p)}>{out?'نفد المخزون':<><CartIcon/>أضف للسلة</>}</button></div></article>})}</div><nav className="wishlist-bottom-nav"><Link to="/" className="nav-item">الرئيسية</Link><Link to="/categories" className="nav-item">الأقسام</Link><Link to="/cart" className="nav-item"><CartIcon size={20}/>السلة</Link><Link to="/account" className="nav-item active">حسابي</Link></nav></div>;
}
